import { images } from "@/assets/images";
import type { HubPage } from "@/content/types";

export const brandingCreativeHub: HubPage = {
  slug: "branding-creative",
  navLabel: "Branding & Creative",
  order: 8,
  priority: "P1",
  h1: "Branding Agency on Koh Phangan",
  primaryKeyword: "branding agency Koh Phangan",
  metaTitle: "Branding Agency Koh Phangan | Identity & Design",
  metaDescription:
    "Brand identity, graphic design, creative direction and menu design for Koh Phangan businesses — original, editorial, built to last.",
  directAnswer:
    "CreativeLAB builds brand identities and creative direction for Koh Phangan businesses — strategy, visual identity, graphic design and menu design — original work built to differentiate you from generic template-based competitors.",
  heroSupport:
    "Brand identity, graphic design, creative direction and menu design, built as a coherent system.",
  heroImage: images.studio,
  heroImageAlt: "Brand identity materials laid out in a design studio",
  editorialTitle: "A brand is a system, not a logo",
  editorialBody: [
    "Many island businesses have a logo but not a brand — inconsistent colors, fonts and tone across their website, social media and printed materials that quietly undermine trust.",
    "We build brand identity as a full system: strategy, visual identity and clear applications across every channel, then apply it consistently through our own web, social and print work so it actually gets used, not just delivered as a PDF.",
  ],
  faqs: [
    { q: "Do you only design logos, or full brand identities?", a: "Full brand identities — strategy, visual system and applications, not just a logo mark." },
    { q: "Can you apply our brand across our website and social media too?", a: "Yes — our other services (web, social, video) are built to carry the brand system through consistently." },
    { q: "How long does a brand identity project take?", a: "Typically 4–8 weeks depending on scope and how many touchpoints are included." },
    { q: "Do you provide brand guidelines?", a: "Yes, a practical guidelines document covering logo use, color, type and tone." },
    { q: "Can you refresh an existing brand rather than starting from scratch?", a: "Yes — we regularly refine and modernize existing identities rather than replacing them entirely." },
    { q: "Do you design print materials too?", a: "Yes, through our Graphic Design service — menus, signage, packaging and campaign materials." },
  ],
  finalCtaLabel: "Start a Project",
  services: [
    {
      slug: "branding",
      hubSlug: "branding-creative",
      navLabel: "Branding",
      h1: "Brand Identity Design on Koh Phangan",
      primaryKeyword: "branding agency Koh Phangan",
      secondaryTopics: ["brand identity", "visual identity"],
      metaTitle: "Brand Identity Design Koh Phangan",
      metaDescription:
        "Brand identity design for Koh Phangan businesses — strategy, visual identity and applications built as one coherent system.",
      directAnswer:
        "We design brand identities for Koh Phangan businesses — starting from strategy and positioning, through a visual identity system, to practical applications across your website, social media and print materials.",
      heroSupport: "Strategy, visual identity and applications built as one coherent brand system.",
      heroImage: images.studio,
      heroImageAlt: "Brand identity design elements laid out for review",
      scope: [
        { title: "Brand strategy", description: "Positioning, tone of voice and audience definition." },
        { title: "Visual identity", description: "Logo, color palette and typography system." },
        { title: "Applications", description: "How the identity applies across web, social and print." },
        { title: "Brand guidelines", description: "A practical document your team can reference and share." },
      ],
      benefits: [
        { title: "Real differentiation", description: "An original identity, not a template that looks like everyone else's." },
        { title: "Consistency everywhere", description: "One system applied across every channel." },
        { title: "Easier for your team to use", description: "Clear guidelines mean fewer inconsistent decisions later." },
        { title: "A foundation for growth", description: "A system that scales as you add services or locations." },
      ],
      process: [
        { title: "Strategy", description: "Define positioning, audience and tone." },
        { title: "Concept", description: "Initial visual identity directions presented for feedback." },
        { title: "Refine", description: "Develop the chosen direction into a full system." },
        { title: "Deliver", description: "Final files and guidelines handed over." },
      ],
      pricing: [
        { service: "Brand identity (logo + guidelines)", range: "THB 30,000 – 80,000", note: "Per project" },
        { service: "Full brand system (multi-channel applications)", range: "THB 70,000 – 150,000", note: "Includes web, social and print application" },
      ],
      useCases: [
        { title: "New businesses", description: "A complete identity built from the ground up." },
        { title: "Rebrands", description: "Refreshing or replacing an outdated identity." },
        { title: "Expanding businesses", description: "A system that scales across new services or locations." },
      ],
      faqs: [
        { q: "How many logo concepts will we see?", a: "Typically 2–3 distinct directions before refining the chosen one." },
        { q: "Do you research our competitors first?", a: "Yes, competitive and market context inform the strategy phase." },
        { q: "What files do we receive at the end?", a: "Logo files in all standard formats, plus a guidelines document covering color, type and usage." },
        { q: "Can you also apply the brand to our existing website?", a: "Yes, through our Web Design or Redesign services." },
        { q: "How many revision rounds are included?", a: "Typically two structured rounds at the concept stage." },
        { q: "Do you trademark the logo for us?", a: "No — trademark registration should go through a qualified legal professional; we can advise on next steps." },
      ],
      related: [
        { label: "Graphic Design", href: "/branding-creative/graphic-design", description: "Applying the identity across print and digital materials." },
        { label: "Creative Direction", href: "/branding-creative/creative-direction", description: "Ongoing creative oversight for campaigns." },
        { label: "Web Design", href: "/websites-digital/web-design", description: "Bringing the brand to your website." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "graphic-design",
      hubSlug: "branding-creative",
      navLabel: "Graphic Design",
      h1: "Graphic Design on Koh Phangan",
      primaryKeyword: "graphic design Koh Phangan",
      secondaryTopics: ["print", "digital design"],
      metaTitle: "Graphic Design Koh Phangan | Print & Digital",
      metaDescription:
        "Graphic design for Koh Phangan businesses — brand systems, campaign assets, social templates and menu design, print and digital.",
      directAnswer:
        "We design print and digital materials for Koh Phangan businesses — campaign assets, social media templates, signage and packaging — consistent with your brand system across every format.",
      heroSupport: "Print and digital design consistent with your brand system, across every format you need.",
      heroImage: images.studio,
      heroImageAlt: "Graphic design layouts being reviewed",
      scope: [
        { title: "Campaign assets", description: "Design for a specific promotion, event or launch." },
        { title: "Social templates", description: "Reusable design templates for consistent social content." },
        { title: "Print materials", description: "Flyers, signage, packaging and similar print needs." },
        { title: "Brand-consistent execution", description: "Every asset designed within your existing brand system." },
      ],
      benefits: [
        { title: "Consistent visual quality", description: "Every asset reflects the same brand standard." },
        { title: "Faster turnaround with templates", description: "Reusable templates speed up future content production." },
        { title: "Covers print and digital", description: "One design partner across every format you need." },
        { title: "Built on your existing brand", description: "No need to redevelop identity for every new asset." },
      ],
      process: [
        { title: "Brief", description: "Understand the specific asset or campaign need." },
        { title: "Design", description: "Layouts developed within your brand guidelines." },
        { title: "Revise", description: "Refine based on your feedback." },
        { title: "Deliver", description: "Final files in the formats you need, print or digital." },
      ],
      pricing: [
        { service: "Single design asset", range: "THB 2,500 – 8,000", note: "Flyer, social template or similar" },
        { service: "Campaign asset set", range: "THB 10,000 – 25,000", note: "Coordinated set of assets for one campaign" },
      ],
      useCases: [
        { title: "Campaign launches", description: "A coordinated set of assets for a specific promotion." },
        { title: "Ongoing social content", description: "Templates that speed up regular content production." },
        { title: "Print needs", description: "Signage, packaging and other physical materials." },
      ],
      faqs: [
        { q: "Do you need an existing brand identity to start?", a: "It helps significantly; we can also develop one first through our Branding service if you don't have one." },
        { q: "Can you design social media templates we can reuse ourselves?", a: "Yes, editable templates can be part of the deliverable." },
        { q: "What file formats do we receive?", a: "Print-ready files for physical materials, and web-optimized files for digital use." },
        { q: "Do you handle the printing itself?", a: "We prepare print-ready files; printing is typically handled by a local printer of your choice." },
        { q: "How quickly can a single asset be turned around?", a: "Simple assets can often be delivered within a few days; larger campaign sets take longer." },
        { q: "Can this include packaging design?", a: "Yes, packaging design is part of our graphic design scope." },
      ],
      related: [
        { label: "Branding", href: "/branding-creative/branding", description: "The identity system this design work applies." },
        { label: "Menu Design", href: "/branding-creative/menu-design", description: "A specific application for food & beverage brands." },
        { label: "Content Creation", href: "/social-media/content-creation", description: "Photography to pair with design templates." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "creative-direction",
      hubSlug: "branding-creative",
      navLabel: "Creative Direction",
      h1: "Creative Direction on Koh Phangan",
      primaryKeyword: "creative direction Koh Phangan",
      secondaryTopics: ["art direction", "campaign creative"],
      metaTitle: "Creative Direction Koh Phangan | Art Direction",
      metaDescription:
        "Creative direction for Koh Phangan brands and campaigns — concept, visual language and production oversight across every asset.",
      directAnswer:
        "We provide creative direction for Koh Phangan brands and campaigns — developing the concept and visual language, then overseeing production across photography, video and design so every asset feels like part of one coherent campaign.",
      heroSupport: "Concept, visual language and production oversight for a coherent campaign or brand presence.",
      heroImage: images.team,
      heroImageAlt: "Creative director reviewing campaign concepts",
      scope: [
        { title: "Concept development", description: "A clear creative idea underpinning the campaign or brand work." },
        { title: "Visual language", description: "A consistent look and feel across every asset produced." },
        { title: "Production oversight", description: "Guiding photography, video and design toward one vision." },
        { title: "Quality control", description: "Ensuring every deliverable meets the creative standard set." },
      ],
      benefits: [
        { title: "A coherent campaign", description: "Every asset feels connected rather than independently produced." },
        { title: "Higher creative quality", description: "Experienced oversight raises the bar across every deliverable." },
        { title: "Efficient collaboration", description: "One point of creative accountability across multiple production teams." },
        { title: "Confidence in the outcome", description: "A clear creative vision reduces guesswork mid-project." },
      ],
      process: [
        { title: "Brief", description: "Understand the campaign or brand goal." },
        { title: "Concept", description: "Develop and present the creative direction." },
        { title: "Oversee production", description: "Guide photography, video and design toward the concept." },
        { title: "Review & refine", description: "Quality control across all final assets." },
      ],
      pricing: [
        { service: "Creative direction (single campaign)", range: "THB 15,000 – 40,000", note: "Concept + production oversight" },
        { service: "Ongoing creative direction", range: "THB 20,000 – 45,000 / month", note: "For businesses with continuous production needs" },
      ],
      useCases: [
        { title: "Larger campaigns", description: "Coordinating photography, video and design under one concept." },
        { title: "Businesses with an in-house team", description: "Adding senior creative oversight without a full-time hire." },
        { title: "Rebrand rollouts", description: "Ensuring a new identity is applied consistently everywhere." },
      ],
      faqs: [
        { q: "Do you also produce the assets, or just direct?", a: "Both are available — direction alone, or paired with our own photography, video and design production." },
        { q: "Can you direct a shoot with our own photographer?", a: "Yes, we can provide creative direction for external production teams." },
        { q: "How is this different from Branding?", a: "Branding builds the underlying identity system; Creative Direction applies and extends it into specific campaigns and productions." },
        { q: "Is this a one-off or ongoing service?", a: "Both options are available depending on your needs." },
        { q: "What deliverables do we get from the direction itself?", a: "Creative concepts, mood boards or treatments, and oversight documentation as relevant to the project." },
        { q: "Can you direct video and photography in the same project?", a: "Yes, this is one of the most common creative direction scenarios." },
      ],
      related: [
        { label: "Branding", href: "/branding-creative/branding", description: "The identity system creative direction builds on." },
        { label: "Commercial Video", href: "/video-production/commercial", description: "Video production this direction can oversee." },
        { label: "Content Creation", href: "/social-media/content-creation", description: "Photography production this direction can oversee." },
      ],
      finalCtaLabel: "Discuss Your Project",
    },
    {
      slug: "menu-design",
      hubSlug: "branding-creative",
      navLabel: "Menu Design",
      h1: "Menu Design for Food & Beverage Brands on Koh Phangan",
      primaryKeyword: "menu design Koh Phangan",
      secondaryTopics: ["restaurant design", "food branding"],
      metaTitle: "Menu Design Koh Phangan | Restaurant & Food Branding",
      metaDescription:
        "Menu design as part of a food and beverage brand identity on Koh Phangan — print and digital, built for hierarchy and brand consistency.",
      directAnswer:
        "We design menus as part of a food or beverage brand's wider identity system on Koh Phangan — building the layout, typography and hierarchy to be consistent with the brand's visual identity, not as a standalone document disconnected from the rest of the business.",
      heroSupport: "Menu design built as part of your brand's wider visual identity system.",
      heroImage: images.food,
      heroImageAlt: "Menu design consistent with a restaurant brand identity",
      scope: [
        { title: "Brand-consistent layout", description: "A menu that reflects the same visual identity as your other materials." },
        { title: "Typography & hierarchy", description: "Readable structure that also carries the brand's tone." },
        { title: "Print & digital formats", description: "Files ready for both physical and digital use." },
        { title: "Ongoing update templates", description: "A structure that makes future menu changes straightforward." },
      ],
      benefits: [
        { title: "One consistent brand experience", description: "The menu reinforces the same identity as your signage, website and social media." },
        { title: "Elevated perceived quality", description: "Considered design signals a more premium experience." },
        { title: "Easier future updates", description: "A reusable structure for seasonal or ongoing menu changes." },
        { title: "Built alongside your full identity", description: "Designed with the same team responsible for your wider brand." },
      ],
      process: [
        { title: "Brand alignment", description: "Confirm how the menu should reflect your existing identity." },
        { title: "Layout design", description: "Structure and hierarchy drafted for review." },
        { title: "Revisions", description: "Refine based on feedback." },
        { title: "Final files", description: "Print-ready and digital files delivered." },
      ],
      pricing: [
        { service: "Menu design (brand-integrated)", range: "THB 8,000 – 20,000", note: "As part of an existing brand identity" },
        { service: "Menu design + brand identity", range: "THB 35,000 – 90,000", note: "Developing both together" },
      ],
      useCases: [
        { title: "New food & beverage brands", description: "Menu design developed alongside a new identity." },
        { title: "Rebrands", description: "Updating the menu to match a refreshed brand." },
        { title: "Multi-venue restaurant groups", description: "Consistent menu design across several locations." },
      ],
      faqs: [
        { q: "How is this different from the Menu Design service under Food & Restaurants?", a: "This version is built as part of a wider brand identity project; the Food & Restaurants version is a standalone menu design project without a full rebrand." },
        { q: "Do you need to design our full brand identity first?", a: "Not necessarily, but the result is stronger when the menu is built alongside a defined identity." },
        { q: "Can you include food photography as well?", a: "Yes, through our Food Photography or Menu Photography services." },
        { q: "Do you handle printing?", a: "We prepare print-ready files; printing is typically handled by a local printer of your choice." },
        { q: "How many revision rounds are included?", a: "Typically two rounds of revisions are included." },
        { q: "Can this include a digital/QR menu version too?", a: "Yes, both print and digital formats are part of the standard scope." },
      ],
      related: [
        { label: "Branding", href: "/branding-creative/branding", description: "The wider identity system this menu design supports." },
        { label: "Menu Design", href: "/food-restaurants/menu-design", description: "The standalone, restaurant-focused version of this service." },
        { label: "Food Photography", href: "/food-restaurants/food-photography", description: "Photography to feature on the menu." },
      ],
      finalCtaLabel: "Request a Quote",
    },
  ],
};
