import { images } from "@/assets/images";
import type { HubPage } from "@/content/types";

export const businessLocalPresenceHub: HubPage = {
  slug: "business-local-presence",
  navLabel: "Business & Local Presence",
  order: 5,
  priority: "P0",
  h1: "Local SEO on Koh Phangan",
  primaryKeyword: "local SEO Koh Phangan",
  metaTitle: "Local SEO Koh Phangan | Google Business Profile & Maps",
  metaDescription:
    "Local SEO, Google Business Profile, Maps optimization, reviews, reputation and listings management for Koh Phangan businesses.",
  directAnswer:
    "CreativeLAB helps Koh Phangan businesses get found locally — Google Business Profile and Maps optimization, review and reputation management, and consistent business listings — the visibility work that sits behind every 'near me' search.",
  heroSupport:
    "Google Business Profile, Maps, reviews, reputation and listings for businesses that want to be found locally.",
  heroImage: images.studio,
  heroImageAlt: "Local business shown on a Google Maps search",
  editorialTitle: "The visibility work most businesses skip",
  editorialBody: [
    "Many Koh Phangan businesses have a website and Instagram, but an incomplete or inactive Google Business Profile, inconsistent listings, or reviews that go unanswered — all of which quietly cost visibility in local search and Maps.",
    "This work is unglamorous but foundational: it's often what determines whether a business shows up at all when someone searches 'near me' — before any content or advertising even gets a chance to work.",
  ],
  faqs: [
    { q: "Is this the same as SEO for my website?", a: "It overlaps — Local SEO focuses specifically on local search and Maps visibility, while Technical SEO (in Websites & Digital) covers your website itself." },
    { q: "Can you fix a Google Business Profile that's already set up incorrectly?", a: "Yes — auditing and correcting an existing profile is one of the most common starting points." },
    { q: "Do you respond to reviews on our behalf?", a: "Yes, as part of Reviews and Reputation management, in your voice and with your approval on sensitive responses." },
    { q: "How long does it take to see results in local search?", a: "Some fixes (accurate categories, complete profile info) help quickly; ranking improvements typically build over 1–3 months." },
    { q: "Do you manage this across multiple business locations?", a: "Yes, we manage local presence across as many locations as you operate." },
    { q: "Can this work alongside our website and social media?", a: "Yes — local presence, website SEO and social media reinforce each other and we coordinate across all three." },
  ],
  finalCtaLabel: "Start a Project",
  services: [
    {
      slug: "local-seo",
      hubSlug: "business-local-presence",
      navLabel: "Local SEO",
      h1: "Local SEO on Koh Phangan",
      primaryKeyword: "local SEO Koh Phangan",
      secondaryTopics: ["local search visibility", "local citations"],
      metaTitle: "Local SEO Koh Phangan | CreativeLAB",
      metaDescription:
        "Local SEO for Koh Phangan businesses — technical basics, relevance and visibility across Google Maps and local search.",
      directAnswer:
        "We improve how Koh Phangan businesses appear in local search and Google Maps — fixing technical basics, aligning your online presence with relevant local search intent, and building the consistent signals Google uses to rank local results.",
      heroSupport: "Technical fixes and consistent signals that improve local search and Maps visibility.",
      heroImage: images.studio,
      heroImageAlt: "Local search results shown on a mobile phone",
      scope: [
        { title: "Local SEO audit", description: "A review of your current visibility, profile and listings." },
        { title: "On-page local signals", description: "Location and service relevance reflected clearly on your website." },
        { title: "Google Business Profile alignment", description: "Ensuring your profile supports, not contradicts, your SEO." },
        { title: "Citation consistency", description: "Business name, address and phone number aligned across directories." },
      ],
      benefits: [
        { title: "Better 'near me' visibility", description: "Improved chances of appearing in local and Maps search results." },
        { title: "Consistent business information", description: "Fewer conflicting listings that confuse both customers and Google." },
        { title: "Compounding results", description: "Local SEO improvements tend to build over time rather than fade." },
        { title: "Works with what you already have", description: "We build on your existing profile and website rather than starting over." },
      ],
      process: [
        { title: "Audit", description: "Review current local search presence and identify gaps." },
        { title: "Fix technical basics", description: "Correct inconsistencies across your website and listings." },
        { title: "Strengthen signals", description: "Improve profile completeness, categories and relevance." },
        { title: "Monitor", description: "Track visibility and refine over time." },
      ],
      pricing: [
        { service: "Local SEO audit", range: "THB 8,000 – 15,000", note: "One-time, with a written action plan" },
        { service: "Ongoing local SEO", range: "THB 10,000 – 25,000 / month", note: "Continuous improvement and monitoring" },
      ],
      useCases: [
        { title: "Service businesses", description: "Improve visibility for 'near me' and service-specific searches." },
        { title: "Restaurants & retail", description: "Stronger presence in local discovery searches." },
        { title: "Multi-location businesses", description: "Consistent local SEO across every location." },
      ],
      faqs: [
        { q: "How is Local SEO different from Google Business Profile management?", a: "Google Business Profile is one input to Local SEO; Local SEO also covers your website's local relevance and listing consistency more broadly." },
        { q: "Do you guarantee a specific ranking position?", a: "No — we never fabricate ranking guarantees; we focus on the concrete work that improves visibility." },
        { q: "How long before I see results?", a: "Some improvements show within weeks; meaningful ranking changes typically take 1–3 months." },
        { q: "Do I need a website for Local SEO to work?", a: "It helps significantly — we can also help build one through our Websites & Digital team if you don't have one." },
        { q: "Can this help with multiple service areas, not just one town?", a: "Yes, we can structure your presence to reflect multiple areas you genuinely serve." },
        { q: "How do you report progress?", a: "Regular reporting on visibility, profile performance and any technical fixes completed." },
      ],
      related: [
        { label: "Google Business Profile", href: "/business-local-presence/google-business-profile", description: "The core profile behind local search visibility." },
        { label: "Google Maps", href: "/business-local-presence/google-maps", description: "Maps-specific optimization." },
        { label: "Technical SEO", href: "/websites-digital/technical-seo", description: "Website-side SEO fundamentals." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "google-business-profile",
      hubSlug: "business-local-presence",
      navLabel: "Google Business Profile",
      h1: "Google Business Profile Optimization on Koh Phangan",
      primaryKeyword: "Google Business Profile Koh Phangan",
      secondaryTopics: ["GBP optimization", "Google Business"],
      metaTitle: "Google Business Profile Koh Phangan | GBP Setup",
      metaDescription:
        "Google Business Profile setup and optimization for Koh Phangan businesses — categories, photos, posts and reviews managed properly.",
      directAnswer:
        "We set up and optimize Google Business Profiles for Koh Phangan businesses — accurate categories, complete information, regular photos and posts, and a proper review response process, so your profile actively helps visibility instead of sitting dormant.",
      heroSupport: "A complete, actively-managed Google Business Profile instead of a dormant listing.",
      heroImage: images.studio,
      heroImageAlt: "Google Business Profile shown on a laptop screen",
      scope: [
        { title: "Profile setup or claim", description: "Claiming and verifying your profile if not already done." },
        { title: "Category & attribute accuracy", description: "Correct categories and attributes that match what you offer." },
        { title: "Photos & posts", description: "Regular photo updates and posts about offers, events or news." },
        { title: "Review monitoring", description: "Tracking and flagging new reviews for response." },
      ],
      benefits: [
        { title: "A profile that works for you", description: "An active, complete profile performs meaningfully better than a neglected one." },
        { title: "More accurate first impression", description: "Correct categories and photos set the right expectations before contact." },
        { title: "Supports local ranking", description: "One of the clearest signals Google uses for local search results." },
        { title: "Less admin for you", description: "We handle ongoing updates so the profile doesn't go stale." },
      ],
      process: [
        { title: "Claim & audit", description: "Verify ownership and review current profile completeness." },
        { title: "Optimize", description: "Correct categories, attributes, hours and information." },
        { title: "Maintain", description: "Ongoing photos, posts and monitoring." },
        { title: "Report", description: "Regular updates on profile performance." },
      ],
      pricing: [
        { service: "Google Business Profile setup/audit", range: "THB 5,000 – 10,000", note: "One-time" },
        { service: "Ongoing GBP management", range: "THB 6,000 – 15,000 / month", note: "Posts, photos, monitoring" },
      ],
      useCases: [
        { title: "New businesses", description: "A properly set up profile from day one." },
        { title: "Existing but neglected profiles", description: "Fixing an outdated or incomplete listing." },
        { title: "Multi-location businesses", description: "Consistent management across each location's profile." },
      ],
      faqs: [
        { q: "What if I've lost access to my existing profile?", a: "We can help you recover or reclaim ownership through Google's verification process." },
        { q: "How often should the profile be updated?", a: "Regular photo and post updates — at least a few times a month — keep a profile active and relevant." },
        { q: "Can you add products or services to the profile?", a: "Yes, where the profile format supports it for your business category." },
        { q: "Do you handle verification if Google flags the listing?", a: "Yes, we can guide you through re-verification if needed." },
        { q: "Is this useful even if I already rank well?", a: "Yes — an active, well-maintained profile also improves conversion once people find you." },
        { q: "Does this include responding to reviews?", a: "Review monitoring is included; response management is part of our dedicated Reviews service." },
      ],
      related: [
        { label: "Google Maps", href: "/business-local-presence/google-maps", description: "Maps-specific visibility building on the same profile." },
        { label: "Reviews", href: "/business-local-presence/reviews", description: "Managing reviews that appear on your profile." },
        { label: "Local SEO", href: "/business-local-presence/local-seo", description: "The broader local search strategy." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "google-maps",
      hubSlug: "business-local-presence",
      navLabel: "Google Maps",
      h1: "Google Maps Optimization on Koh Phangan",
      primaryKeyword: "Google Maps optimization Koh Phangan",
      secondaryTopics: ["Maps marketing", "local visibility"],
      metaTitle: "Google Maps Optimization Koh Phangan",
      metaDescription:
        "Google Maps optimization for Koh Phangan businesses — accurate listings, categories, reviews, photos and directions.",
      directAnswer:
        "We optimize how Koh Phangan businesses appear on Google Maps — accurate pin placement, categories, photos and directions information, so customers can actually find you and trust what they see before arriving.",
      heroSupport: "Accurate, complete Maps listings that customers can actually find and trust.",
      heroImage: images.studio,
      heroImageAlt: "Business location pinned on Google Maps",
      scope: [
        { title: "Pin accuracy", description: "Correcting inaccurate or imprecise location pins." },
        { title: "Category optimization", description: "Selecting categories that best match how customers search." },
        { title: "Photos & directions", description: "Clear photos and directions information for easy arrival." },
        { title: "Review visibility", description: "Ensuring reviews display correctly and are being monitored." },
      ],
      benefits: [
        { title: "Customers find you correctly", description: "An accurate pin avoids lost customers and bad first impressions." },
        { title: "Stronger local discovery", description: "Maps is often the first touchpoint for local searches." },
        { title: "Builds trust before arrival", description: "Clear photos and information set accurate expectations." },
        { title: "Fewer support headaches", description: "Fewer 'we couldn't find you' calls and messages." },
      ],
      process: [
        { title: "Audit", description: "Check pin accuracy, categories and current listing quality." },
        { title: "Correct", description: "Fix inaccuracies and strengthen listing information." },
        { title: "Enhance", description: "Add photos and clear directions information." },
        { title: "Monitor", description: "Ongoing checks as Maps data or your business details change." },
      ],
      pricing: [
        { service: "Google Maps optimization", range: "THB 4,000 – 9,000", note: "One-time correction and optimization" },
      ],
      useCases: [
        { title: "Hard-to-find locations", description: "Businesses in areas where GPS accuracy is often poor." },
        { title: "New locations", description: "Ensuring accurate Maps presence from opening." },
        { title: "Businesses that moved", description: "Correcting outdated location information after relocating." },
      ],
      faqs: [
        { q: "Why does my pin show the wrong location?", a: "This is a common issue on Koh Phangan due to inconsistent address data; we correct it directly through Google's tools." },
        { q: "Can you add a business logo or cover photo to the map listing?", a: "Yes, as part of the broader profile optimization." },
        { q: "Does this help with delivery drivers finding us?", a: "Yes, accurate Maps data also improves delivery and rideshare navigation to your location." },
        { q: "How long does a pin correction take to update?", a: "Google's review process can take from a few days to a few weeks, depending on the change." },
        { q: "Is this separate from Google Business Profile management?", a: "It's closely related — Maps optimization is one part of a well-managed Google Business Profile." },
        { q: "Can you fix duplicate listings for the same business?", a: "Yes, identifying and merging or removing duplicate listings is part of this service." },
      ],
      related: [
        { label: "Google Business Profile", href: "/business-local-presence/google-business-profile", description: "The profile behind your Maps listing." },
        { label: "Listings", href: "/business-local-presence/listings", description: "Consistency across other directories too." },
        { label: "Local SEO", href: "/business-local-presence/local-seo", description: "The broader local visibility strategy." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "reviews",
      hubSlug: "business-local-presence",
      navLabel: "Reviews",
      h1: "Google Reviews Management on Koh Phangan",
      primaryKeyword: "Google reviews management Koh Phangan",
      secondaryTopics: ["customer reviews", "review strategy"],
      metaTitle: "Google Reviews Management Koh Phangan",
      metaDescription:
        "Review request process, response management and monitoring for Koh Phangan businesses on Google and other platforms.",
      directAnswer:
        "We help Koh Phangan businesses build a steady flow of genuine reviews and respond to them properly — a simple request process for happy customers, thoughtful responses (including to criticism), and ongoing monitoring across platforms.",
      heroSupport: "A steady request process and thoughtful responses — never fabricated reviews.",
      heroImage: images.team,
      heroImageAlt: "Business owner reviewing customer feedback",
      scope: [
        { title: "Review request process", description: "A simple, ethical system for asking satisfied customers to leave a review." },
        { title: "Response management", description: "Timely, professional responses to both positive and negative reviews." },
        { title: "Monitoring", description: "Tracking new reviews across Google and other relevant platforms." },
        { title: "Reporting", description: "Regular summaries of review volume, sentiment and response status." },
      ],
      benefits: [
        { title: "More genuine reviews over time", description: "A consistent request process outperforms occasional, ad hoc asking." },
        { title: "Better handling of criticism", description: "Thoughtful responses to negative reviews often repair the relationship publicly." },
        { title: "Improved local trust and ranking", description: "Review volume and recency both influence how customers and Google view you." },
        { title: "Nothing goes unanswered", description: "Consistent monitoring means no review sits ignored." },
      ],
      process: [
        { title: "Set up the request process", description: "Build a simple system for requesting reviews at the right moment." },
        { title: "Monitor", description: "Track incoming reviews across platforms." },
        { title: "Respond", description: "Draft and post responses, with your approval on sensitive cases." },
        { title: "Report", description: "Regular summary of review activity and trends." },
      ],
      pricing: [
        { service: "Review management setup", range: "THB 5,000 – 10,000", note: "One-time — request process and initial audit" },
        { service: "Ongoing review management", range: "THB 6,000 – 15,000 / month", note: "Monitoring and responses" },
      ],
      useCases: [
        { title: "Restaurants & hospitality", description: "High review volume that needs consistent, timely responses." },
        { title: "Service businesses", description: "Building initial review volume and credibility." },
        { title: "Businesses recovering reputation", description: "Handling a run of negative reviews professionally." },
      ],
      faqs: [
        { q: "Can you get us fake or paid reviews?", a: "No — we never fabricate or purchase reviews; this violates platform policy and our own Truth Rule. We only build a genuine request process." },
        { q: "How do you handle an unfair or false negative review?", a: "We draft a calm, professional response and can advise on flagging it to the platform if it violates guidelines — we don't fabricate a rebuttal." },
        { q: "Do I need to approve every response before it's posted?", a: "We recommend approval for negative or sensitive reviews; routine positive responses can be handled directly." },
        { q: "Which platforms do you monitor besides Google?", a: "We can include TripAdvisor, Facebook and relevant booking platforms depending on your business type." },
        { q: "How quickly do you respond to new reviews?", a: "Typically within 24–48 hours, prioritizing negative reviews for faster response." },
        { q: "Can this help improve an already-damaged reputation?", a: "It's part of the solution — see our Reputation service for a more complete approach." },
      ],
      related: [
        { label: "Reputation", href: "/business-local-presence/reputation", description: "Broader reputation monitoring and management." },
        { label: "Google Business Profile", href: "/business-local-presence/google-business-profile", description: "Where most reviews are managed from." },
        { label: "Local SEO", href: "/business-local-presence/local-seo", description: "How reviews feed into local search visibility." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "reputation",
      hubSlug: "business-local-presence",
      navLabel: "Reputation",
      h1: "Online Reputation Management on Koh Phangan",
      primaryKeyword: "online reputation management Koh Phangan",
      secondaryTopics: ["brand reputation", "review management"],
      metaTitle: "Online Reputation Management Koh Phangan",
      metaDescription:
        "Reputation monitoring, response and consistency management for Koh Phangan businesses across review platforms and social media.",
      directAnswer:
        "We monitor and manage online reputation for Koh Phangan businesses across reviews, social media and search — flagging issues early, coordinating consistent, honest responses, and escalating anything that needs your direct attention.",
      heroSupport: "Monitoring, response and escalation that protects your reputation across every platform.",
      heroImage: images.team,
      heroImageAlt: "Team reviewing brand reputation across platforms",
      scope: [
        { title: "Cross-platform monitoring", description: "Tracking mentions and reviews across Google, social media and relevant platforms." },
        { title: "Response coordination", description: "Consistent tone and message across every response." },
        { title: "Escalation process", description: "A clear process for flagging serious issues that need your direct input." },
        { title: "Consistency checks", description: "Ensuring your public information stays accurate everywhere." },
      ],
      benefits: [
        { title: "Nothing catches you off guard", description: "Early monitoring means issues get addressed before they escalate." },
        { title: "Consistent public voice", description: "Every response reflects the same tone and standards." },
        { title: "Faster resolution", description: "A clear escalation process gets serious issues to you quickly." },
        { title: "Protects long-term trust", description: "Proactive management protects reputation built over years." },
      ],
      process: [
        { title: "Baseline audit", description: "Review current reputation across platforms." },
        { title: "Set up monitoring", description: "Track mentions and reviews continuously." },
        { title: "Respond & escalate", description: "Handle routine items directly, escalate serious ones." },
        { title: "Report", description: "Regular summary of reputation trends and actions taken." },
      ],
      pricing: [
        { service: "Reputation monitoring & management", range: "THB 10,000 – 25,000 / month", note: "Cross-platform monitoring and response" },
      ],
      useCases: [
        { title: "Established businesses", description: "Ongoing protection of a reputation built over years." },
        { title: "Businesses facing a specific issue", description: "Managing the response to a particular incident or complaint pattern." },
        { title: "Multi-location brands", description: "Consistent reputation management across every location." },
      ],
      faqs: [
        { q: "Can you remove negative reviews or content?", a: "We can help flag content that violates a platform's policies, but we never fabricate removal guarantees or manipulate reviews." },
        { q: "How is this different from your Reviews service?", a: "Reviews focuses specifically on the review request and response process; Reputation covers broader monitoring across reviews, social media and mentions." },
        { q: "What counts as an issue that gets escalated to me?", a: "Anything legally sensitive, factually disputed, or requiring a decision only you can make." },
        { q: "Can you help after a specific reputation incident?", a: "Yes — we can build a focused response plan for a particular situation." },
        { q: "Do you monitor competitor mentions too?", a: "This can be scoped separately if competitive monitoring is useful to you." },
        { q: "How often will I receive updates?", a: "Regular reporting, plus immediate flagging of anything urgent." },
      ],
      related: [
        { label: "Reviews", href: "/business-local-presence/reviews", description: "The review-specific side of reputation management." },
        { label: "Google Business Profile", href: "/business-local-presence/google-business-profile", description: "A key surface for public reputation." },
        { label: "Instagram Management", href: "/social-media/instagram-management", description: "Reputation on your social channels." },
      ],
      finalCtaLabel: "Discuss Your Project",
    },
    {
      slug: "listings",
      hubSlug: "business-local-presence",
      navLabel: "Listings",
      h1: "Business Listings Management on Koh Phangan",
      primaryKeyword: "business listings Koh Phangan",
      secondaryTopics: ["local citations", "directories"],
      metaTitle: "Business Listings Koh Phangan | Local Citations",
      metaDescription:
        "Business listing and citation management for Koh Phangan businesses — consistent NAP data across relevant directories.",
      directAnswer:
        "We manage business listings and citations for Koh Phangan businesses — making sure your name, address and phone number are consistent across relevant directories, and cleaning up duplicate or outdated listings that confuse customers and search engines alike.",
      heroSupport: "Consistent business information across every directory that matters.",
      heroImage: images.studio,
      heroImageAlt: "Business directory listing shown on a screen",
      scope: [
        { title: "Listing audit", description: "Identify where your business is currently listed, correctly or not." },
        { title: "NAP consistency", description: "Aligning name, address and phone number across every listing." },
        { title: "Relevant directories", description: "Focusing on directories that actually matter for your business type and location." },
        { title: "Duplicate cleanup", description: "Merging or removing outdated and duplicate listings." },
      ],
      benefits: [
        { title: "Clearer signal to search engines", description: "Consistent data supports better local search performance." },
        { title: "Less customer confusion", description: "No more outdated addresses or phone numbers circulating online." },
        { title: "Time saved", description: "We handle the tedious cross-directory cleanup work." },
        { title: "A stronger foundation", description: "Clean listings support every other local visibility effort." },
      ],
      process: [
        { title: "Audit", description: "Find every existing listing for your business." },
        { title: "Correct", description: "Update inaccurate information across each directory." },
        { title: "Clean up", description: "Merge or remove duplicate and outdated listings." },
        { title: "Monitor", description: "Periodic checks to catch new inconsistencies." },
      ],
      pricing: [
        { service: "Listings audit & cleanup", range: "THB 6,000 – 14,000", note: "One-time, covers relevant directories" },
      ],
      useCases: [
        { title: "Businesses that rebranded or moved", description: "Cleaning up outdated information left across the web." },
        { title: "New businesses", description: "Establishing accurate listings from the start." },
        { title: "Multi-location businesses", description: "Consistency across every location's listings." },
      ],
      faqs: [
        { q: "Which directories do you focus on?", a: "The ones genuinely relevant to your business type and location, not a generic mass list — quality over quantity." },
        { q: "How do duplicate listings happen?", a: "Often from past changes in ownership, address or name, or third-party directories auto-generating listings." },
        { q: "Will this improve my search ranking?", a: "It supports local SEO as one contributing factor — not a standalone ranking guarantee." },
        { q: "How long does a full listings cleanup take?", a: "Typically 2–4 weeks, since some directories require manual verification." },
        { q: "Do you monitor for new duplicate listings going forward?", a: "Periodic monitoring can be included in an ongoing Local SEO arrangement." },
        { q: "Is this needed if I only operate on Google/Maps?", a: "It's still useful — inconsistent data elsewhere can still confuse customers and indirectly affect trust signals." },
      ],
      related: [
        { label: "Local SEO", href: "/business-local-presence/local-seo", description: "The broader strategy this work supports." },
        { label: "Google Maps", href: "/business-local-presence/google-maps", description: "Your most important single listing." },
        { label: "Google Business Profile", href: "/business-local-presence/google-business-profile", description: "Core profile management." },
      ],
      finalCtaLabel: "Request a Quote",
    },
  ],
};
