import { images } from "@/assets/images";
import type { HubPage } from "@/content/types";

export const foodRestaurantsHub: HubPage = {
  slug: "food-restaurants",
  navLabel: "Food & Restaurants",
  order: 4,
  priority: "P0",
  h1: "Restaurant Marketing on Koh Phangan",
  primaryKeyword: "restaurant marketing Koh Phangan",
  metaTitle: "Restaurant Marketing Koh Phangan | Food Photography & Ads",
  metaDescription:
    "Food photography, menu design, social media and advertising for restaurants and cafés on Koh Phangan — from a single shoot to full marketing.",
  directAnswer:
    "CreativeLAB helps restaurants and cafés on Koh Phangan get found and fill tables — food and menu photography, styling, menu design, social media, advertising and websites built around the full customer journey, from discovery to reservation.",
  heroSupport:
    "Food photography, menu design, social media and advertising for restaurants that want fuller tables, not just nicer photos.",
  heroImage: images.food,
  heroImageAlt: "Styled plate of food photographed for a restaurant",
  editorialTitle: "Marketing built around how diners actually choose",
  editorialBody: [
    "On Koh Phangan, most diners decide where to eat from Google Maps photos, Instagram and a friend's recommendation, often within minutes of getting hungry. A restaurant's visual presence carries more weight than its menu wording.",
    "We treat food photography, menu design, social content and advertising as one connected system rather than separate purchases — so a dish photographed for the menu also works on Instagram, Google Business Profile and in paid ads.",
  ],
  faqs: [
    { q: "Do you only take photos, or can you help with the whole marketing side?", a: "Both — from a single food photography shoot through to full restaurant marketing including social and advertising." },
    { q: "Can you help us launch a new menu?", a: "Yes — menu photography, design and a coordinated social and advertising push around the launch." },
    { q: "Do you understand the seasonality of restaurant business on Koh Phangan?", a: "Yes — we plan content and campaigns around the island's tourist seasons and local demand patterns." },
    { q: "Can you manage our Google Business Profile too?", a: "Yes, through our Business & Local Presence hub — it pairs closely with restaurant marketing." },
    { q: "Do you offer ongoing monthly support, not just one-off projects?", a: "Yes — most restaurant clients move to a monthly content and marketing arrangement after an initial project." },
    { q: "Can you shoot delivery-platform-ready photos too?", a: "Yes — we deliver images sized and styled appropriately for delivery apps as well as your own menu and social channels." },
  ],
  finalCtaLabel: "Start a Project",
  services: [
    {
      slug: "food-photography",
      hubSlug: "food-restaurants",
      navLabel: "Food Photography",
      h1: "Food Photography on Koh Phangan",
      primaryKeyword: "food photography Koh Phangan",
      secondaryTopics: ["commercial food photography"],
      metaTitle: "Food Photography Koh Phangan | CreativeLAB",
      metaDescription:
        "Commercial food photography for Koh Phangan restaurants — styling, lighting and formats ready for menus, delivery apps and social media.",
      directAnswer:
        "We photograph food for restaurants and cafés on Koh Phangan — styled, well-lit images ready for menus, delivery platforms and social media, shot to make dishes look genuinely appetizing rather than generic.",
      heroSupport: "Styled, appetizing food photography ready for menus, delivery apps and social media.",
      heroImage: images.food,
      heroImageAlt: "Chef's dish styled and photographed for a restaurant menu",
      scope: [
        { title: "Styling consultation", description: "Guidance on plating and presentation before the shoot." },
        { title: "Lighting & composition", description: "Professional lighting suited to each dish's texture and color." },
        { title: "Multi-format delivery", description: "Images sized for menus, delivery apps and social media." },
        { title: "Editing", description: "Color-accurate retouching that keeps food looking real, not artificial." },
      ],
      benefits: [
        { title: "More appetizing menu presence", description: "Well-lit, styled photography noticeably outperforms phone snapshots." },
        { title: "Consistent across platforms", description: "The same quality standard on your menu, Google listing and Instagram." },
        { title: "Reusable across channels", description: "One shoot supplies menu, delivery app and social content." },
        { title: "Built for delivery platforms too", description: "Formats matched to what delivery apps actually need." },
      ],
      process: [
        { title: "Menu review", description: "Agree which dishes to shoot and in what order." },
        { title: "Styling", description: "Light plating adjustments made on-site for the camera." },
        { title: "Shoot", description: "Each dish photographed fresh, in sequence." },
        { title: "Edit & deliver", description: "Retouched images delivered in the sizes you need." },
      ],
      pricing: [
        { service: "Food photography (per dish)", range: "THB 1,500 – 4,000", note: "Styling included" },
        { service: "Full menu shoot (15–25 dishes)", range: "THB 15,000 – 35,000", note: "Half to full day" },
      ],
      useCases: [
        { title: "New restaurant launches", description: "A complete photographed menu from day one." },
        { title: "Menu refreshes", description: "Updated photography when dishes change seasonally." },
        { title: "Delivery-focused restaurants", description: "Photography built specifically for delivery app listings." },
      ],
      faqs: [
        { q: "Do you bring your own styling props?", a: "Yes, we bring a basic styling kit; distinctive tableware from your restaurant adds authenticity." },
        { q: "How many dishes can you shoot in one session?", a: "Typically 10–20 dishes in a half to full day, depending on complexity." },
        { q: "Do you shoot on-site at the restaurant?", a: "Yes, on-site is standard so dishes are fresh and lighting matches your actual space." },
        { q: "Can you match our existing brand's photography style?", a: "Yes, we'll review any existing photography and match tone and styling." },
        { q: "How long until we receive final images?", a: "Typically 3–5 business days after the shoot." },
        { q: "Can this be combined with menu design?", a: "Yes, through our Menu Design service using the same photography." },
      ],
      related: [
        { label: "Menu Photography", href: "/food-restaurants/menu-photography", description: "A focused shoot for a printed or digital menu." },
        { label: "Food Styling", href: "/food-restaurants/food-styling", description: "Dedicated styling support for a shoot." },
        { label: "Menu Design", href: "/food-restaurants/menu-design", description: "Turn the photography into a finished menu." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "menu-photography",
      hubSlug: "food-restaurants",
      navLabel: "Menu Photography",
      h1: "Menu Photography on Koh Phangan",
      primaryKeyword: "menu photography Koh Phangan",
      secondaryTopics: ["dish photography", "delivery menu"],
      metaTitle: "Menu Photography Koh Phangan | Print & Delivery Ready",
      metaDescription:
        "A consistent, platform-ready photo set for your printed or digital menu and delivery app listings on Koh Phangan.",
      directAnswer:
        "We shoot a consistent, complete photo set for your printed or digital menu — every dish photographed to the same standard, delivered in the exact formats your menu design and delivery platforms need.",
      heroSupport: "A complete, consistent photo set built specifically for your menu.",
      heroImage: images.food,
      heroImageAlt: "Menu items photographed in a consistent style",
      scope: [
        { title: "Full-menu coverage", description: "Every menu item photographed to the same visual standard." },
        { title: "Consistent framing", description: "A repeatable angle and crop so the menu feels cohesive." },
        { title: "Print & digital sizing", description: "Files delivered for both printed menus and digital display." },
        { title: "Delivery-platform sets", description: "Cropped versions matched to delivery app image requirements." },
      ],
      benefits: [
        { title: "A cohesive menu", description: "Consistent photography makes the whole menu feel considered, not patchwork." },
        { title: "Ready for every channel", description: "Print, digital menu boards and delivery apps covered from one shoot." },
        { title: "Easier updates later", description: "New dishes can be shot to match the existing set going forward." },
        { title: "Stronger delivery listings", description: "Delivery apps convert better with accurate, appetizing photos." },
      ],
      process: [
        { title: "Menu audit", description: "Confirm the full item list and any priority dishes." },
        { title: "Shoot", description: "Every dish shot to a consistent standard." },
        { title: "Edit", description: "Consistent color and crop applied across the set." },
        { title: "Deliver", description: "Organized files matched to your menu format and platforms." },
      ],
      pricing: [
        { service: "Menu photography set (up to 20 items)", range: "THB 12,000 – 28,000", note: "Consistent full-menu set" },
        { service: "Menu photography set (20+ items)", range: "THB 28,000 – 45,000", note: "Larger menus, multiple sessions" },
      ],
      useCases: [
        { title: "Printed menus", description: "A complete photo set for a physical menu redesign." },
        { title: "Digital menu boards", description: "Consistent imagery for screens and digital displays." },
        { title: "Delivery platforms", description: "A full, accurate photo set across every listed item." },
      ],
      faqs: [
        { q: "Can this cover our entire menu in one shoot?", a: "For most menus, yes across one to two sessions depending on size." },
        { q: "What if we add new dishes later?", a: "We can shoot additions later, matching the original style for consistency." },
        { q: "Do you also design the menu layout?", a: "Yes, through our Menu Design service." },
        { q: "What file formats do we receive?", a: "High-resolution files for print plus web-optimized versions for digital and delivery use." },
        { q: "Can you shoot drinks and desserts too?", a: "Yes, the full menu including drinks, desserts and specials." },
        { q: "How is this different from general Food Photography?", a: "Menu Photography specifically covers a complete, consistent set for a menu; Food Photography can be a smaller or more editorial selection." },
      ],
      related: [
        { label: "Menu Design", href: "/food-restaurants/menu-design", description: "Turn the photography into a finished menu." },
        { label: "Food Photography", href: "/food-restaurants/food-photography", description: "Editorial or social-focused food photography." },
        { label: "Restaurant Website", href: "/food-restaurants/website", description: "Publish the menu online." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "food-styling",
      hubSlug: "food-restaurants",
      navLabel: "Food Styling",
      h1: "Food Styling on Koh Phangan",
      primaryKeyword: "food stylist Koh Phangan",
      secondaryTopics: ["food styling", "commercial styling"],
      metaTitle: "Food Stylist Koh Phangan | Commercial Food Styling",
      metaDescription:
        "Professional food styling for commercial photography and video on Koh Phangan — composition, props and shoot preparation.",
      directAnswer:
        "We provide food styling for commercial photography and video shoots on Koh Phangan — plating composition, prop selection and shoot preparation that makes food photograph well without looking artificial.",
      heroSupport: "Plating, props and preparation that make food photograph and film well.",
      heroImage: images.food,
      heroImageAlt: "Food stylist arranging a dish before a photo shoot",
      scope: [
        { title: "Plating composition", description: "Arranging each dish for the strongest possible shot." },
        { title: "Prop selection", description: "Tableware, linens and backgrounds suited to your brand." },
        { title: "Shoot preparation", description: "Prepping ingredients and dishes to hold up under studio or on-site lighting." },
        { title: "On-set collaboration", description: "Working alongside the photographer or videographer throughout the shoot." },
      ],
      benefits: [
        { title: "Food that looks like itself, only better", description: "Styling enhances real dishes rather than faking them." },
        { title: "Consistent visual brand", description: "Props and composition matched to your restaurant's identity." },
        { title: "Smoother shoot days", description: "Preparation keeps dishes camera-ready for longer." },
        { title: "Works for photo and video", description: "The same styling expertise applies to both formats." },
      ],
      process: [
        { title: "Pre-shoot planning", description: "Agree the visual direction and any props needed." },
        { title: "Prep", description: "Ingredients and dishes prepared for camera-readiness." },
        { title: "On-set styling", description: "Continuous plating adjustments throughout the shoot." },
        { title: "Wrap", description: "Final checks against the shot list before finishing." },
      ],
      pricing: [
        { service: "Food styling (half-day, with our photographer)", range: "Included in photography package", note: "Bundled with Food Photography by default" },
        { service: "Food styling (standalone, your own crew)", range: "THB 6,000 – 15,000", note: "Styling only, for an external shoot" },
      ],
      useCases: [
        { title: "Menu & marketing shoots", description: "Styling for a professional food photography session." },
        { title: "Video production", description: "Styling support for commercial or social video shoots." },
        { title: "Brand campaigns", description: "Consistent styling across a larger advertising campaign." },
      ],
      faqs: [
        { q: "Do I need to book styling separately from photography?", a: "No — it's included by default in our Food Photography service; standalone styling is for shoots with an external crew." },
        { q: "Can you style for video, not just photos?", a: "Yes, styling applies equally to video production." },
        { q: "Do you provide props, or do we?", a: "We bring a base kit of props and can source specific items if your brand needs something particular." },
        { q: "How long does styling take per dish?", a: "A few minutes per dish once prep is done, though the first setup of a shoot takes longer." },
        { q: "Can you style drinks and desserts too?", a: "Yes, styling covers the full range of menu items." },
        { q: "Do you style for delivery-app photography differently?", a: "Yes — delivery photography favors clarity and accuracy over highly artistic composition." },
      ],
      related: [
        { label: "Food Photography", href: "/food-restaurants/food-photography", description: "The photography this styling supports." },
        { label: "Menu Photography", href: "/food-restaurants/menu-photography", description: "A full-menu shoot using the same styling approach." },
        { label: "Social Video", href: "/video-production/social-video", description: "Styled food for short-form video content." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "menu-design",
      hubSlug: "food-restaurants",
      navLabel: "Menu Design",
      h1: "Restaurant Menu Design on Koh Phangan",
      primaryKeyword: "restaurant menu design Koh Phangan",
      secondaryTopics: ["menu graphic design", "digital menu"],
      metaTitle: "Restaurant Menu Design Koh Phangan | Print & Digital",
      metaDescription:
        "Menu design for Koh Phangan restaurants — print and digital layouts built for readability and brand consistency.",
      directAnswer:
        "We design printed and digital menus for Koh Phangan restaurants — layouts built for readability, priced items that guide attention sensibly, and a look consistent with your restaurant's branding.",
      heroSupport: "Menu layouts built for readability and brand consistency, print or digital.",
      heroImage: images.studio,
      heroImageAlt: "Restaurant menu design laid out on a desk",
      scope: [
        { title: "Layout design", description: "A clear structure that guides diners through the menu logically." },
        { title: "Typography & hierarchy", description: "Readable type and pricing that doesn't fight for attention." },
        { title: "Print-ready files", description: "Files prepared correctly for your printer of choice." },
        { title: "Digital versions", description: "A digital or QR-friendly version for online display." },
      ],
      benefits: [
        { title: "Easier to read, easier to order from", description: "Good hierarchy can influence what diners choose." },
        { title: "Consistent with your brand", description: "Matches your restaurant's visual identity, not a generic template." },
        { title: "Print and digital covered", description: "One design system across both formats." },
        { title: "Update-friendly", description: "Structured files make future menu changes straightforward." },
      ],
      process: [
        { title: "Content collection", description: "Gather final dish names, descriptions and prices." },
        { title: "Layout design", description: "Structure and hierarchy drafted for review." },
        { title: "Revisions", description: "Refine based on your feedback." },
        { title: "Final files", description: "Print-ready and digital files delivered." },
      ],
      pricing: [
        { service: "Menu design (single page)", range: "THB 5,000 – 12,000", note: "Print or digital" },
        { service: "Menu design (multi-page/section)", range: "THB 12,000 – 25,000", note: "Larger or multi-category menus" },
      ],
      useCases: [
        { title: "New restaurant openings", description: "A complete menu design as part of launch." },
        { title: "Rebrands", description: "Updating an existing menu to match a new identity." },
        { title: "Seasonal menu changes", description: "Refreshed layouts as dishes and pricing change." },
      ],
      faqs: [
        { q: "Do you write the menu descriptions too?", a: "We can refine wording for clarity and consistency; core dish descriptions typically come from you or your chef." },
        { q: "Can you design a QR-code digital menu?", a: "Yes, a digital-first layout suited to phone screens and QR access." },
        { q: "How many revision rounds are included?", a: "Typically two rounds of revisions are included; further changes can be scoped separately." },
        { q: "Do you handle the printing?", a: "We prepare print-ready files; printing itself is usually handled by a local printer of your choice." },
        { q: "Can this include photography?", a: "Yes, paired with our Food or Menu Photography for a fully photographed menu." },
        { q: "How long does a menu design project take?", a: "Typically 1–2 weeks depending on content readiness and revision rounds." },
      ],
      related: [
        { label: "Menu Photography", href: "/food-restaurants/menu-photography", description: "Photography to include in the design." },
        { label: "Branding", href: "/branding-creative/branding", description: "Full brand identity beyond the menu." },
        { label: "Restaurant Website", href: "/food-restaurants/website", description: "A digital home for your menu." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "social",
      hubSlug: "food-restaurants",
      navLabel: "Restaurant Social",
      h1: "Restaurant Social Media on Koh Phangan",
      primaryKeyword: "restaurant social media Koh Phangan",
      secondaryTopics: ["Instagram", "Reels", "content"],
      metaTitle: "Restaurant Social Media Koh Phangan | Instagram & Reels",
      metaDescription:
        "Social media management for Koh Phangan restaurants — content calendar, production and community management built for fuller tables.",
      directAnswer:
        "We manage social media for restaurants and cafés on Koh Phangan — a content calendar built around your menu, events and offers, produced and published consistently, with community management that keeps diners engaged.",
      heroSupport: "A content calendar, production and community management built for a busy restaurant.",
      heroImage: images.social,
      heroImageAlt: "Restaurant social media content being reviewed",
      scope: [
        { title: "Content calendar", description: "Planned posts tied to your menu, events and offers." },
        { title: "Production", description: "Photo and video content for feed, Stories and Reels." },
        { title: "Publishing", description: "Consistent posting across the month." },
        { title: "Community management", description: "Responding to comments and messages in your voice." },
      ],
      benefits: [
        { title: "Consistent visibility", description: "A steady presence instead of sporadic posting." },
        { title: "Drives real visits", description: "Content built around your actual menu and offers, not generic food content." },
        { title: "Handles the busy nights", description: "You keep running the restaurant while we manage the account." },
        { title: "Works with your other marketing", description: "Coordinated with photography, ads and your Google presence." },
      ],
      process: [
        { title: "Plan", description: "Build a content calendar around your calendar of events and offers." },
        { title: "Produce", description: "Photo and video content shot regularly." },
        { title: "Publish", description: "Scheduled posting throughout the month." },
        { title: "Review", description: "Monthly check-in on what's working." },
      ],
      pricing: [
        { service: "Restaurant social package (light)", range: "THB 14,000 – 22,000 / month", note: "3 posts/week + Stories" },
        { service: "Restaurant social package (full)", range: "THB 24,000 – 40,000 / month", note: "5+ posts/week, Reels, community management" },
      ],
      useCases: [
        { title: "Restaurants & cafés", description: "Consistent presence showcasing food, atmosphere and events." },
        { title: "Bars & venues", description: "Event promotion and nightlife-focused content." },
        { title: "Multi-location groups", description: "Coordinated social presence across several venues." },
      ],
      faqs: [
        { q: "Do you shoot new content regularly, or reuse existing photos?", a: "We shoot new content on a regular cadence to keep the feed current, supplementing with existing assets where useful." },
        { q: "Can you promote specific events or offers?", a: "Yes, event and offer promotion is a core part of restaurant social content." },
        { q: "Do you handle reservations through social media?", a: "We can direct diners to your booking channel; managing the bookings themselves is outside this service." },
        { q: "Can this include paid advertising too?", a: "Advertising is a separate service (Restaurant Advertising) that we coordinate closely with social content." },
        { q: "How do you measure success for a restaurant account?", a: "Engagement, reach, and where trackable, reservation or foot-traffic impact." },
        { q: "Is this different from your general Social Media hub services?", a: "It's the same core service, tailored specifically to restaurant content and cadence." },
      ],
      related: [
        { label: "Food Photography", href: "/food-restaurants/food-photography", description: "The photography behind the content." },
        { label: "Restaurant Advertising", href: "/food-restaurants/advertising", description: "Paid promotion alongside organic content." },
        { label: "Reels", href: "/social-media/reels", description: "Short-form video for menu and event highlights." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "advertising",
      hubSlug: "food-restaurants",
      navLabel: "Restaurant Advertising",
      h1: "Restaurant Advertising on Koh Phangan",
      primaryKeyword: "restaurant advertising Koh Phangan",
      secondaryTopics: ["Meta Ads", "Google Ads", "local advertising"],
      metaTitle: "Restaurant Advertising Koh Phangan | Meta & Google Ads",
      metaDescription:
        "Advertising for restaurants on Koh Phangan — Meta and Google Ads campaigns built around offers, events and local targeting.",
      directAnswer:
        "We run advertising campaigns for restaurants on Koh Phangan — Meta and Google Ads built around specific offers, events or menu launches, targeted to the right local and traveller audiences, with tracking to see what actually drove visits.",
      heroSupport: "Meta and Google Ads campaigns built around your offers, events and menu.",
      heroImage: images.studio,
      heroImageAlt: "Restaurant offer being prepared for an ad campaign",
      scope: [
        { title: "Offer strategy", description: "Choosing what to promote and to whom." },
        { title: "Ad creative", description: "Food photography and video adapted into ad formats." },
        { title: "Targeting", description: "Location, interest and timing targeting suited to a restaurant's audience." },
        { title: "Tracking", description: "Measuring reach, engagement and, where possible, visits or bookings." },
      ],
      benefits: [
        { title: "Fill specific slow periods", description: "Target advertising around quiet nights or seasons." },
        { title: "Promote launches effectively", description: "Get a new menu or event in front of the right people fast." },
        { title: "Local-first targeting", description: "Reach people actually near your restaurant, not a broad generic audience." },
        { title: "Built on strong creative", description: "Ads use the same quality photography and video as your other marketing." },
      ],
      process: [
        { title: "Define the offer", description: "Agree what's being promoted and the goal." },
        { title: "Build creative", description: "Ad assets produced or adapted from existing content." },
        { title: "Launch", description: "Campaign goes live with local and relevant targeting." },
        { title: "Optimize & report", description: "Adjustments made based on real performance." },
      ],
      pricing: [
        { service: "Restaurant ad campaign setup", range: "THB 8,000 – 18,000", note: "One-time — strategy, creative, setup" },
        { service: "Monthly ad management", range: "THB 8,000 – 18,000 / month", note: "Excludes ad spend" },
      ],
      useCases: [
        { title: "New menu or dish launches", description: "Get an offer in front of a relevant local audience fast." },
        { title: "Slow-season promotion", description: "Targeted campaigns to fill quiet nights or weeks." },
        { title: "Event promotion", description: "Advertise a specific night, live event or special occasion." },
      ],
      faqs: [
        { q: "Which platform works best for restaurant advertising?", a: "Usually Meta (Facebook/Instagram) for visual, local reach, sometimes paired with Google Ads for active searchers." },
        { q: "Can you target tourists currently on the island specifically?", a: "Yes, location-based targeting can focus on people currently near Koh Phangan." },
        { q: "Do you need new photography for every campaign?", a: "Not necessarily — existing food photography and video can often be adapted into new ad creative." },
        { q: "How much should I budget for ad spend?", a: "Most restaurants start testing with a modest monthly budget; we'll recommend a realistic figure based on your goal." },
        { q: "Can this promote a specific event or one-off night?", a: "Yes, short-term campaigns are common for one-off events." },
        { q: "How is success measured for a restaurant campaign?", a: "Reach, engagement and, where trackable, reservations, redemptions or foot traffic." },
      ],
      related: [
        { label: "Restaurant Social", href: "/food-restaurants/social", description: "Organic content to pair with paid advertising." },
        { label: "Meta Ads", href: "/advertising/meta-ads", description: "The underlying advertising service." },
        { label: "Food Photography", href: "/food-restaurants/food-photography", description: "Creative assets for your campaigns." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "website",
      hubSlug: "food-restaurants",
      navLabel: "Restaurant Website",
      h1: "Restaurant Website Design on Koh Phangan",
      primaryKeyword: "restaurant website Koh Phangan",
      secondaryTopics: ["menu website", "booking", "ordering"],
      metaTitle: "Restaurant Website Koh Phangan | Menu, Booking & SEO",
      metaDescription:
        "Restaurant websites on Koh Phangan built around the menu, location, booking or ordering journey and local SEO.",
      directAnswer:
        "We build restaurant websites on Koh Phangan structured around what diners actually need — the menu, location and hours, and a clear path to book a table or order, with the on-page SEO to be found when people search for a place to eat.",
      heroSupport:
        "A website built around your menu, location and booking journey, as part of your restaurant's marketing.",
      heroImage: images.food,
      heroImageAlt: "Restaurant website displayed on a laptop screen",
      scope: [
        { title: "Menu integration", description: "Your menu presented clearly, easy to browse on mobile." },
        { title: "Location & hours", description: "Clear, prominent details for finding and visiting you." },
        { title: "Booking or ordering path", description: "A direct link to your reservation or ordering system." },
        { title: "Local SEO basics", description: "On-page structure that supports being found in local search." },
      ],
      benefits: [
        { title: "One clear conversion path", description: "Diners can find your menu, location and booking option quickly." },
        { title: "Mobile-first", description: "Built for the phone browsing most diners actually use." },
        { title: "Supports your other marketing", description: "A proper landing point for social, ads and Google Business Profile links." },
        { title: "Findable in search", description: "Structured for local search visibility from launch." },
      ],
      process: [
        { title: "Discovery", description: "Confirm menu, booking/ordering system and content." },
        { title: "Design", description: "A layout matched to your restaurant's identity." },
        { title: "Build", description: "Development with mobile performance as a priority." },
        { title: "Launch", description: "Site goes live with SEO basics in place." },
      ],
      pricing: [
        { service: "Restaurant website (single page)", range: "THB 25,000 – 45,000", note: "Menu, location, booking link" },
        { service: "Restaurant website (multi-page)", range: "THB 45,000 – 90,000", note: "Adds gallery, events, blog/journal" },
      ],
      useCases: [
        { title: "New restaurant launches", description: "A proper web presence from opening day." },
        { title: "Restaurants without a real website", description: "Replacing a social-media-only presence with a real site." },
        { title: "Multi-location restaurants", description: "A site structured to represent several venues clearly." },
      ],
      faqs: [
        { q: "Can you integrate our existing booking or delivery system?", a: "Yes, we link to or embed most common reservation and ordering platforms." },
        { q: "Do you write the website copy?", a: "Yes, following our copy rules — no invented claims, clear and useful content." },
        { q: "Will the site work well on phones?", a: "Yes, mobile performance is a priority given how most diners browse." },
        { q: "Can this include online ordering directly, not just a link?", a: "Full e-commerce ordering is scoped through our E-commerce service; most restaurant sites link to a dedicated ordering platform instead." },
        { q: "Do you handle hosting and maintenance after launch?", a: "We can set this up and hand over, or continue supporting it — we'll agree what fits your situation." },
        { q: "How long does a restaurant website project take?", a: "Typically 3–6 weeks depending on scope and content readiness." },
      ],
      related: [
        { label: "Menu Design", href: "/food-restaurants/menu-design", description: "A designed menu to feature on the site." },
        { label: "Local SEO", href: "/business-local-presence/local-seo", description: "Broader local search visibility beyond the website." },
        { label: "Web Design", href: "/websites-digital/web-design", description: "Our general web design service." },
      ],
      finalCtaLabel: "Request a Quote",
    },
  ],
};
