import { images } from "@/assets/images";
import type { HubPage } from "@/content/types";

export const villasRealEstateHub: HubPage = {
  slug: "villas-real-estate",
  navLabel: "Villas & Real Estate",
  order: 3,
  priority: "P0",
  h1: "Villa & Real Estate Photography on Koh Phangan",
  primaryKeyword: "villa photography Koh Phangan",
  metaTitle: "Villa & Real Estate Photography Koh Phangan",
  metaDescription:
    "Villa, land and architecture photography, drone, video, virtual tours and full property marketing for Koh Phangan real estate.",
  directAnswer:
    "CreativeLAB photographs and markets villas, land and property developments on Koh Phangan — interiors, exteriors, drone, property video, virtual tours and full listing-ready marketing for owners, agents and developers.",
  heroSupport:
    "Villa photography, drone, video and full property marketing for Koh Phangan real estate.",
  heroImage: images.photoshoot,
  heroImageAlt: "Photographer capturing a villa exterior on Koh Phangan",
  editorialTitle: "Listing-ready visuals for a competitive market",
  editorialBody: [
    "Koh Phangan's villa and land market moves fast, and most buyers or renters make their first judgment from photos alone. Weak or inconsistent imagery costs viewings before a single message is sent.",
    "We shoot and produce property content built for how it's actually used — listing platforms, social media, and direct outreach — so a single shoot covers photography, video and social content instead of separate vendors for each.",
  ],
  faqs: [
    {
      q: "Do you work with real estate agencies as well as individual owners?",
      a: "Yes — we regularly shoot for agencies, developers and independent owners, adapting delivery to each platform's requirements.",
    },
    {
      q: "Can you shoot a property that's still under construction?",
      a: "Yes, for progress documentation and marketing; final listing photography is best once the property is styled and complete.",
    },
    {
      q: "Do you provide drone photography for every property?",
      a: "Where it adds real value and is legally permitted — not every property benefits from aerial shots, and we'll advise honestly.",
    },
    {
      q: "How long does a typical villa shoot take?",
      a: "Most villas take half a day to a full day depending on size and whether video and drone are included.",
    },
    {
      q: "Can you help with the property's marketing beyond photography?",
      a: "Yes, through our Real Estate Marketing service — listings, social content and advertising built around the same visuals.",
    },
    {
      q: "Do you stage the property before shooting?",
      a: "We advise on styling and can coordinate light staging, but full interior styling is outside our scope unless agreed separately.",
    },
  ],
  finalCtaLabel: "Start a Project",
  services: [
    {
      slug: "villa-photography",
      hubSlug: "villas-real-estate",
      navLabel: "Villa Photography",
      h1: "Villa Photography on Koh Phangan",
      primaryKeyword: "villa photography Koh Phangan",
      secondaryTopics: ["luxury villa photography", "property photography"],
      metaTitle: "Villa Photography Koh Phangan | CreativeLAB",
      metaDescription:
        "Listing-ready villa photography on Koh Phangan — interiors, exteriors and composition built to sell or rent the property faster.",
      directAnswer:
        "We photograph villas on Koh Phangan for sale and rental listings — interiors, exteriors and composition built to show the property at its best, delivered ready for listing platforms and social media.",
      heroSupport: "Interior and exterior villa photography built for listings that get booked.",
      heroImage: images.photoshoot,
      heroImageAlt: "Interior of a Koh Phangan villa photographed for a listing",
      scope: [
        { title: "Interior photography", description: "Living spaces, bedrooms and bathrooms shot to feel spacious and inviting." },
        { title: "Exterior photography", description: "Facades, pool areas and outdoor living spaces in the best available light." },
        { title: "Detail shots", description: "Finishes and features that differentiate the property." },
        { title: "Editing & delivery", description: "Color-corrected, retouched images delivered in listing-ready sizes." },
      ],
      benefits: [
        { title: "Faster bookings or sales", description: "Strong photography is consistently linked to shorter time-on-market." },
        { title: "Platform-ready delivery", description: "Images sized and formatted for Airbnb, agency sites and social media alike." },
        { title: "Consistent quality", description: "Every room shot with the same lighting and composition standard." },
        { title: "One shoot, multiple uses", description: "The same images serve listings, social content and advertising." },
      ],
      process: [
        { title: "Pre-shoot check", description: "Review the property and agree timing for the best natural light." },
        { title: "Shoot", description: "Interior and exterior photography across the property." },
        { title: "Edit", description: "Color correction, straightening and retouching." },
        { title: "Deliver", description: "Final images delivered in the sizes each platform needs." },
      ],
      pricing: [
        { service: "1–3 bedroom villa", range: "THB 6,000 – 12,000", note: "Half-day shoot, ~25–40 final images" },
        { service: "4+ bedroom villa", range: "THB 12,000 – 22,000", note: "Full-day shoot, larger image set" },
      ],
      useCases: [
        { title: "Villa owners renting short-term", description: "Listing photography for Airbnb and booking platforms." },
        { title: "Villas for sale", description: "Sales-ready imagery for agents and marketing." },
        { title: "Property managers", description: "Consistent photography across a portfolio of villas." },
      ],
      faqs: [
        { q: "What time of day do you shoot?", a: "Usually early morning or late afternoon for the best natural light, adjusted to the property's orientation." },
        { q: "Do you edit out clutter or personal items?", a: "We ask that spaces be tidied before the shoot; light retouching is included, but styling is a separate conversation." },
        { q: "How many final images will I receive?", a: "Typically 25–40 for a standard villa, depending on size — we'll agree a number before the shoot." },
        { q: "Can you shoot at sunset for exterior shots?", a: "Yes, this is often recommended for pool and outdoor living area photography." },
        { q: "Do you include drone shots?", a: "Drone photography is a separate service and can be added to the same shoot day." },
        { q: "What's the turnaround time for final images?", a: "Typically 3–5 business days after the shoot." },
      ],
      related: [
        { label: "Drone", href: "/villas-real-estate/drone", description: "Add aerial photography to the same shoot." },
        { label: "Property Video", href: "/villas-real-estate/property-video", description: "A walkthrough video alongside the photography." },
        { label: "Real Estate Marketing", href: "/villas-real-estate/marketing", description: "Turn the shoot into a full marketing package." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "real-estate-photography",
      hubSlug: "villas-real-estate",
      navLabel: "Real Estate Photography",
      h1: "Real Estate Photography on Koh Phangan",
      primaryKeyword: "real estate photography Koh Phangan",
      secondaryTopics: ["property photography", "listing photography"],
      metaTitle: "Real Estate Photography Koh Phangan",
      metaDescription:
        "Sale and rental-ready real estate photography on Koh Phangan for agencies, developers and private owners.",
      directAnswer:
        "We provide real estate photography for sale and rental listings across Koh Phangan — houses, apartments, condos and commercial properties — shot to a consistent standard agencies and developers can rely on across a portfolio.",
      heroSupport: "Consistent, listing-ready photography for agencies, developers and private sellers.",
      heroImage: images.photoshoot,
      heroImageAlt: "Real estate property exterior photographed for a listing",
      scope: [
        { title: "Interior & exterior coverage", description: "Full property coverage suited to the listing type." },
        { title: "Consistent standards", description: "A repeatable process for agencies managing multiple listings." },
        { title: "Fast turnaround", description: "Editing timelines that match listing deadlines." },
        { title: "Flexible licensing", description: "Usage terms suited to agency and multi-platform listing needs." },
      ],
      benefits: [
        { title: "Portfolio consistency", description: "The same visual standard across every listing an agency manages." },
        { title: "Faster time to market", description: "Quick turnaround keeps listings moving without delay." },
        { title: "Trust with buyers", description: "Professional photography signals a serious, credible listing." },
        { title: "One local partner", description: "A reliable photography partner based on the island, not flown in." },
      ],
      process: [
        { title: "Scheduling", description: "Coordinate access and timing around the listing deadline." },
        { title: "Shoot", description: "Full property coverage, interior and exterior." },
        { title: "Edit", description: "Consistent color and correction standards applied." },
        { title: "Deliver", description: "Files delivered in the format your listing platform requires." },
      ],
      pricing: [
        { service: "Standard property shoot", range: "THB 5,000 – 10,000", note: "Apartment, condo or small house" },
        { service: "Agency portfolio rate", range: "Custom", note: "Volume pricing for ongoing listing work" },
      ],
      useCases: [
        { title: "Real estate agencies", description: "Consistent photography across an active listing portfolio." },
        { title: "Developers", description: "Sales-ready imagery for units and show homes." },
        { title: "Private sellers", description: "Professional photography for a one-off sale." },
      ],
      faqs: [
        { q: "Do you offer agency rates for regular work?", a: "Yes — we can agree a standing rate for agencies with recurring listing photography needs." },
        { q: "How quickly can you turn around a shoot before a listing deadline?", a: "Rush turnaround is possible with advance notice; standard delivery is 3–5 business days." },
        { q: "Do you photograph commercial and residential properties?", a: "Yes, both — the approach is adapted to the property type." },
        { q: "Can you shoot multiple units in one development on the same day?", a: "Yes, and this is typically the most cost-effective approach for developers." },
        { q: "Do you provide floor plans or only photography?", a: "Photography is our focus; we can coordinate with a separate floor plan provider if needed." },
        { q: "What licensing do we get for the images?", a: "Standard licensing covers listing and marketing use; ask about extended commercial licensing if needed." },
      ],
      related: [
        { label: "Virtual Tours", href: "/villas-real-estate/virtual-tours", description: "Add a 360 tour to the listing." },
        { label: "Villa Photography", href: "/villas-real-estate/villa-photography", description: "Our villa-specific photography service." },
        { label: "Real Estate Marketing", href: "/villas-real-estate/marketing", description: "Full marketing built around the photography." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "land-photography",
      hubSlug: "villas-real-estate",
      navLabel: "Land Photography",
      h1: "Land Photography on Koh Phangan",
      primaryKeyword: "land photography Koh Phangan",
      secondaryTopics: ["land listing", "aerial land photography"],
      metaTitle: "Land Photography Koh Phangan | Listing & Aerial",
      metaDescription:
        "Land listing photography on Koh Phangan — access, terrain, surroundings and aerial context for buyers evaluating a plot.",
      directAnswer:
        "We photograph land listings on Koh Phangan — showing access, terrain, boundaries and surroundings clearly, with aerial photography where useful, so buyers can properly evaluate a plot before visiting in person.",
      heroSupport: "Ground and aerial photography that shows a plot's terrain, access and surroundings honestly.",
      heroImage: images.video,
      heroImageAlt: "Rural land plot photographed for a real estate listing",
      scope: [
        { title: "Access & boundary shots", description: "Clear documentation of road access and approximate boundaries." },
        { title: "Terrain photography", description: "Slope, vegetation and ground condition shown accurately." },
        { title: "Surroundings", description: "Neighboring context — views, proximity to roads, beach or amenities." },
        { title: "Aerial context", description: "Drone photography where legal and useful for showing the plot's shape and setting." },
      ],
      benefits: [
        { title: "Fewer wasted site visits", description: "Buyers can rule properties in or out with clearer information upfront." },
        { title: "Honest representation", description: "Accurate terrain and access photography builds trust with serious buyers." },
        { title: "Better for remote buyers", description: "International buyers can evaluate a plot without visiting first." },
        { title: "Clear aerial context", description: "Drone shots show shape, slope and surroundings that ground photos miss." },
      ],
      process: [
        { title: "Site visit", description: "Understand the plot's boundaries, access and key features." },
        { title: "Ground photography", description: "Document terrain, access and surroundings." },
        { title: "Aerial photography", description: "Drone shots where permitted and useful." },
        { title: "Deliver", description: "An organized image set covering the plot from every relevant angle." },
      ],
      pricing: [
        { service: "Land photography (ground only)", range: "THB 4,000 – 8,000", note: "Access, terrain and surroundings" },
        { service: "Land photography + drone", range: "THB 8,000 – 15,000", note: "Adds aerial context shots" },
      ],
      useCases: [
        { title: "Land for sale", description: "Photography for private sellers and agencies listing plots." },
        { title: "Development sites", description: "Pre-construction documentation for investors and developers." },
        { title: "Remote/international buyers", description: "Detailed visual context for buyers evaluating from abroad." },
      ],
      faqs: [
        { q: "Can you show road access clearly in the photos?", a: "Yes, this is one of the most important elements we document for land listings." },
        { q: "Is drone photography always included?", a: "It's available as an add-on and recommended for most land listings, but not automatically included." },
        { q: "Can you visit a hard-to-reach plot?", a: "In most cases yes — let us know about access conditions in advance so we can plan accordingly." },
        { q: "Do you provide measurements or surveying?", a: "No — we provide photography only; measurements and surveys should come from a licensed surveyor." },
        { q: "How do you handle land with unclear boundaries?", a: "We photograph based on information the seller provides and clearly avoid implying boundaries we haven't confirmed." },
        { q: "Can this be combined with a listing description?", a: "Yes, through our Real Estate Marketing service." },
      ],
      related: [
        { label: "Drone", href: "/villas-real-estate/drone", description: "Aerial photography for land and property." },
        { label: "Real Estate Marketing", href: "/villas-real-estate/marketing", description: "Full marketing for a land listing." },
        { label: "Architecture Photography", href: "/villas-real-estate/architecture-photography", description: "For plots with existing structures." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "architecture-photography",
      hubSlug: "villas-real-estate",
      navLabel: "Architecture Photography",
      h1: "Architecture Photography on Koh Phangan",
      primaryKeyword: "architecture photography Koh Phangan",
      secondaryTopics: ["architectural photography", "building photography"],
      metaTitle: "Architecture Photography Koh Phangan",
      metaDescription:
        "Architecture photography on Koh Phangan for architects, builders and developers — lines, materials and context, interior and exterior.",
      directAnswer:
        "We photograph buildings and architectural projects on Koh Phangan for architects, builders and developers — capturing lines, materials and spatial context in a style suited to portfolios and publications, not just listings.",
      heroSupport: "Photography that shows a building's design intent, materials and context clearly.",
      heroImage: images.studio,
      heroImageAlt: "Architectural detail photographed with strong composition",
      scope: [
        { title: "Exterior composition", description: "Shots that show the building's form and relationship to its site." },
        { title: "Interior spatial photography", description: "Light, proportion and material captured accurately." },
        { title: "Material & detail shots", description: "Close attention to finishes and construction details." },
        { title: "Portfolio-ready editing", description: "Editing suited to architecture portfolios and publications." },
      ],
      benefits: [
        { title: "Portfolio-quality documentation", description: "Photography suited to architects' and builders' own marketing." },
        { title: "Shows design intent", description: "Composition that respects and communicates the architecture, not just the listing." },
        { title: "Useful for multiple audiences", description: "Portfolio, publication and client marketing from one shoot." },
        { title: "Local availability", description: "No need to fly in a specialist photographer for an island project." },
      ],
      process: [
        { title: "Site visit", description: "Understand the design intent and key views with the architect or builder." },
        { title: "Shoot", description: "Exterior and interior photography planned around light and composition." },
        { title: "Edit", description: "Careful correction of perspective and color for an architectural standard." },
        { title: "Deliver", description: "Portfolio-ready files delivered for print and digital use." },
      ],
      pricing: [
        { service: "Architecture photography (half-day)", range: "THB 8,000 – 15,000", note: "Single building or project" },
        { service: "Architecture photography (full-day)", range: "THB 15,000 – 28,000", note: "Larger project or multiple structures" },
      ],
      useCases: [
        { title: "Architects", description: "Portfolio photography for completed projects." },
        { title: "Builders & contractors", description: "Marketing photography showing build quality." },
        { title: "Developers", description: "Showcasing a development's design for marketing and investors." },
      ],
      faqs: [
        { q: "Do you work directly with architects, or only property owners?", a: "Both — we regularly shoot for architects and builders as well as property owners and developers." },
        { q: "Can you shoot a building at a specific time for the best light?", a: "Yes, we'll recommend the best time of day based on the building's orientation." },
        { q: "Do you photograph interiors as well as exteriors?", a: "Yes, both are typically included in an architecture photography project." },
        { q: "Can this be used for a publication submission?", a: "Yes, editing is done to a standard suitable for portfolios and publication." },
        { q: "How is this different from villa photography?", a: "Architecture photography prioritizes design and composition; villa photography prioritizes listing appeal — the two often overlap." },
        { q: "Do you provide drone shots of the building and site?", a: "Yes, as an add-on where useful and permitted." },
      ],
      related: [
        { label: "Villa Photography", href: "/villas-real-estate/villa-photography", description: "Listing-focused photography for finished villas." },
        { label: "Drone", href: "/villas-real-estate/drone", description: "Aerial context for the building and site." },
        { label: "Branding", href: "/branding-creative/branding", description: "Brand identity for architecture and building firms." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "drone",
      hubSlug: "villas-real-estate",
      navLabel: "Drone",
      h1: "Drone Photography on Koh Phangan",
      primaryKeyword: "drone photography Koh Phangan",
      secondaryTopics: ["aerial photography", "property drone"],
      metaTitle: "Drone Photography Koh Phangan | Aerial Property Shots",
      metaDescription:
        "Drone photography on Koh Phangan for property, land and landscape — aerial context captured safely and within local regulations.",
      directAnswer:
        "We provide drone photography on Koh Phangan for villas, land and developments — aerial shots that show a property's setting, surroundings and scale, captured safely and in line with local drone regulations.",
      heroSupport: "Aerial photography that shows a property's setting, scale and surroundings.",
      heroImage: images.video,
      heroImageAlt: "Drone prepared for an aerial property photography flight",
      scope: [
        { title: "Aerial property shots", description: "Wide establishing shots showing the property and its context." },
        { title: "Land & site aerials", description: "Boundary, terrain and access context from above." },
        { title: "Compliance check", description: "Flight planning that respects local airspace and privacy regulations." },
        { title: "Edited delivery", description: "Color-corrected aerial images delivered alongside ground photography." },
      ],
      benefits: [
        { title: "Context ground shots can't show", description: "Scale, surroundings and layout are clearer from above." },
        { title: "Stronger listings", description: "Aerial shots are consistently among the most engaging listing images." },
        { title: "Safe & compliant", description: "Flights planned and flown within local regulations, not informally." },
        { title: "Pairs with any shoot", description: "Add to villa, land or architecture photography in the same visit." },
      ],
      process: [
        { title: "Flight planning", description: "Check airspace, permissions and weather conditions." },
        { title: "Flight & capture", description: "Aerial photography captured around the rest of the shoot." },
        { title: "Edit", description: "Color correction and selection of the strongest angles." },
        { title: "Deliver", description: "Aerial images delivered alongside ground photography." },
      ],
      pricing: [
        { service: "Drone add-on (with existing shoot)", range: "THB 3,000 – 6,000", note: "Added to a villa/land shoot" },
        { service: "Standalone drone session", range: "THB 6,000 – 12,000", note: "Aerial-only coverage" },
      ],
      useCases: [
        { title: "Villa & land listings", description: "Aerial context alongside standard listing photography." },
        { title: "Developments", description: "Showing scale and layout of a larger site." },
        { title: "Landscape & location marketing", description: "Wider shots of the area surrounding a property." },
      ],
      faqs: [
        { q: "Is drone photography legal on Koh Phangan?", a: "Yes, within Thailand's drone regulations and appropriate permissions — we plan every flight accordingly." },
        { q: "Can you fly near the coast or over the sea?", a: "Yes, subject to local regulations and any restricted zones near the flight location." },
        { q: "What happens if weather doesn't allow flying on the shoot day?", a: "We reschedule the drone portion rather than flying in unsafe conditions." },
        { q: "Do you also offer drone video, not just photos?", a: "Yes, through our Drone Video service — the same flight can often cover both." },
        { q: "Is drone photography included by default in villa shoots?", a: "No, it's an add-on — we'll recommend it where it genuinely improves the listing." },
        { q: "Who owns the drone footage?", a: "You receive full usage rights for your property marketing once the project is delivered." },
      ],
      related: [
        { label: "Drone Video", href: "/video-production/drone-video", description: "Aerial video alongside aerial photography." },
        { label: "Villa Photography", href: "/villas-real-estate/villa-photography", description: "Ground photography to pair with aerial shots." },
        { label: "FPV", href: "/villas-real-estate/fpv", description: "Dynamic FPV drone footage for a more cinematic result." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "property-video",
      hubSlug: "villas-real-estate",
      navLabel: "Property Video",
      h1: "Real Estate Video Production on Koh Phangan",
      primaryKeyword: "real estate video Koh Phangan",
      secondaryTopics: ["villa video", "property film"],
      metaTitle: "Real Estate Video Koh Phangan | Property Walkthroughs",
      metaDescription:
        "Property walkthrough videos on Koh Phangan — atmosphere-led films and vertical social cuts for villas and real estate listings.",
      directAnswer:
        "We produce property walkthrough videos for villas and real estate listings on Koh Phangan — films that convey the atmosphere and flow of a property, delivered as both a full walkthrough and shorter vertical cuts for social media.",
      heroSupport: "Walkthrough films and social cuts that show a property's atmosphere, not just its floor plan.",
      heroImage: images.video,
      heroImageAlt: "Camera operator filming a villa walkthrough",
      scope: [
        { title: "Full walkthrough", description: "A complete filmed tour through the property's key spaces." },
        { title: "Atmosphere & pacing", description: "Editing that conveys how the property actually feels to move through." },
        { title: "Vertical social cuts", description: "Shorter edits formatted for Instagram and TikTok." },
        { title: "Music & sound design", description: "Licensed music and sound treatment suited to the property's style." },
      ],
      benefits: [
        { title: "Shows flow, not just rooms", description: "Video communicates layout and atmosphere better than photos alone." },
        { title: "Works across platforms", description: "One shoot produces both a full walkthrough and social-ready cuts." },
        { title: "Higher engagement", description: "Video listings typically hold attention longer than photo-only listings." },
        { title: "Pairs with photography", description: "Often filmed on the same day as the photography shoot." },
      ],
      process: [
        { title: "Plan the route", description: "Map the walkthrough path and key moments to capture." },
        { title: "Film", description: "Stabilized walkthrough footage plus supporting establishing shots." },
        { title: "Edit", description: "Full-length and short-form vertical cuts edited with music and pacing." },
        { title: "Deliver", description: "Final files delivered in formats for listing sites and social media." },
      ],
      pricing: [
        { service: "Property walkthrough video", range: "THB 15,000 – 30,000", note: "Full walkthrough + 1–2 social cuts" },
        { service: "Video production (60s commercial)", range: "THB 25,000 – 60,000", note: "Higher-production commercial-style edit" },
      ],
      useCases: [
        { title: "Villa rentals", description: "Walkthrough video for booking platforms and social media." },
        { title: "Villas for sale", description: "A stronger sales tool than photography alone for high-value properties." },
        { title: "Developments", description: "Showcase videos for pre-sale marketing." },
      ],
      faqs: [
        { q: "How long is a typical walkthrough video?", a: "Usually 60–120 seconds for the full version, with 15–30 second cuts for social." },
        { q: "Do you use a gimbal or stabilizer for smooth footage?", a: "Yes, stabilized equipment is standard for walkthrough filming." },
        { q: "Can you combine this with drone footage?", a: "Yes — combining ground and aerial footage is common for larger properties." },
        { q: "What music do you use?", a: "Licensed stock music matched to the property's style, or your own if you have rights to use it." },
        { q: "Do you include a voiceover or on-screen text?", a: "On-screen text with key details is available; voiceover can be added on request." },
        { q: "How long does editing take?", a: "Typically 5–10 business days depending on the number of cuts required." },
      ],
      related: [
        { label: "Villa Photography", href: "/villas-real-estate/villa-photography", description: "Photography to pair with the walkthrough video." },
        { label: "FPV", href: "/villas-real-estate/fpv", description: "A more dynamic, cinematic alternative walkthrough style." },
        { label: "Virtual Tours", href: "/villas-real-estate/virtual-tours", description: "A self-navigable alternative to a filmed walkthrough." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "fpv",
      hubSlug: "villas-real-estate",
      navLabel: "FPV",
      h1: "FPV Drone Video on Koh Phangan",
      primaryKeyword: "FPV drone Koh Phangan",
      secondaryTopics: ["FPV property video"],
      metaTitle: "FPV Drone Video Koh Phangan | Property & Real Estate",
      metaDescription:
        "FPV drone video for Koh Phangan properties — dynamic walkthrough-style footage flown safely for suitable properties.",
      directAnswer:
        "We fly FPV (first-person-view) drones to produce dynamic, continuous-motion footage of suitable properties on Koh Phangan — sweeping through spaces and grounds in a single fluid shot that a standard drone or gimbal can't replicate.",
      heroSupport: "Fast, fluid FPV footage for properties where a dynamic, cinematic shot makes sense.",
      heroImage: images.video,
      heroImageAlt: "FPV drone flying through a property for dynamic video",
      scope: [
        { title: "Suitability assessment", description: "An honest check on whether a property and site suit FPV filming safely." },
        { title: "Flight choreography", description: "Planned flight paths through and around the property." },
        { title: "Safety planning", description: "Flights planned around people, structures and regulations." },
        { title: "Edited delivery", description: "Color-graded, music-scored final cuts." },
      ],
      benefits: [
        { title: "A distinctive, premium feel", description: "FPV footage stands out from standard property video." },
        { title: "Shows flow and scale together", description: "One continuous shot can connect interior and exterior spaces." },
        { title: "Strong for marketing hero content", description: "Ideal as a lead video for premium listings." },
        { title: "Flown safely", description: "We only recommend FPV where the site and conditions allow it safely." },
      ],
      process: [
        { title: "Site assessment", description: "Confirm the property and site are suitable and safe for FPV filming." },
        { title: "Flight plan", description: "Choreograph the route through the property." },
        { title: "Fly & capture", description: "Multiple passes flown to get the strongest take." },
        { title: "Edit", description: "Color grading, sound design and final cut delivered." },
      ],
      pricing: [
        { service: "FPV property video", range: "THB 20,000 – 45,000", note: "Depends on property size and complexity" },
      ],
      useCases: [
        { title: "Premium villas", description: "A standout hero video for a high-value listing." },
        { title: "Developments with dramatic sites", description: "Showing scale and setting in one continuous flow." },
        { title: "Marketing campaigns", description: "Distinctive video content for advertising and social." },
      ],
      faqs: [
        { q: "Is FPV suitable for every property?", a: "No — some sites don't suit it safely or visually; we'll advise honestly rather than force it." },
        { q: "How is FPV different from standard drone video?", a: "FPV drones are flown manually in first-person view for fast, fluid, close-proximity shots standard drones can't achieve." },
        { q: "Is FPV filming safe around people and buildings?", a: "Yes, when flown by an experienced pilot with a proper flight plan — safety is assessed before every flight." },
        { q: "Can FPV combine with standard drone and ground footage?", a: "Yes, this combination often produces the strongest overall video." },
        { q: "How long does an FPV shoot take?", a: "Typically half a day including planning, multiple flight passes and safety checks." },
        { q: "What's the turnaround for the edited video?", a: "Usually 5–10 business days." },
      ],
      related: [
        { label: "Property Video", href: "/villas-real-estate/property-video", description: "A standard walkthrough video alternative." },
        { label: "Drone", href: "/villas-real-estate/drone", description: "Static aerial photography of the same property." },
        { label: "FPV Video", href: "/video-production/fpv-video", description: "FPV video production for non-real-estate projects." },
      ],
      finalCtaLabel: "Discuss Your Project",
    },
    {
      slug: "virtual-tours",
      hubSlug: "villas-real-estate",
      navLabel: "Virtual Tours",
      h1: "360° Virtual Tours on Koh Phangan",
      primaryKeyword: "360 virtual tour Koh Phangan",
      secondaryTopics: ["property virtual tour"],
      metaTitle: "360 Virtual Tours Koh Phangan | Property Listings",
      metaDescription:
        "360° virtual tours for Koh Phangan properties — self-navigable tours for remote viewing, embedded directly into your listing.",
      directAnswer:
        "We produce 360° virtual tours for Koh Phangan properties, letting remote buyers and renters navigate a property room by room from anywhere — embedded directly into your listing page or shared as a standalone link.",
      heroSupport: "Self-navigable 360° tours that let remote buyers explore a property before they arrive.",
      heroImage: images.studio,
      heroImageAlt: "360-degree camera capturing a property interior",
      scope: [
        { title: "360° capture", description: "Room-by-room photography stitched into a navigable tour." },
        { title: "Navigation setup", description: "Logical room-to-room navigation matched to the property's layout." },
        { title: "Listing integration", description: "Embed code or link for your listing page or platform." },
        { title: "Hosting", description: "Hosted tour link that works across devices without an app." },
      ],
      benefits: [
        { title: "Remote viewing that works", description: "International buyers can properly explore a property before booking a visit." },
        { title: "Fewer wasted viewings", description: "Serious interest is easier to confirm before an in-person visit." },
        { title: "Modern, credible presentation", description: "A virtual tour signals a serious, well-marketed listing." },
        { title: "Works on any device", description: "No app download required for viewers." },
      ],
      process: [
        { title: "Plan the route", description: "Map which rooms and spaces the tour should cover." },
        { title: "Capture", description: "360° images captured at each tour point." },
        { title: "Stitch & configure", description: "Tour assembled with working navigation between points." },
        { title: "Deliver & embed", description: "Link or embed code delivered for your listing." },
      ],
      pricing: [
        { service: "Virtual tour (standard villa)", range: "THB 8,000 – 16,000", note: "Up to ~10 tour points" },
        { service: "Virtual tour (larger property)", range: "THB 16,000 – 28,000", note: "10+ tour points" },
      ],
      useCases: [
        { title: "International buyers/renters", description: "Serious remote viewing before travel." },
        { title: "Premium listings", description: "A differentiator for high-value villas." },
        { title: "Agencies", description: "A standard offering across an agency's listing portfolio." },
      ],
      faqs: [
        { q: "Do viewers need to download an app?", a: "No — tours run in a standard web browser on desktop or mobile." },
        { q: "How long does capturing a tour take?", a: "Typically 1–3 hours depending on the property's size and number of rooms." },
        { q: "Can the tour be embedded on my own website?", a: "Yes, we provide an embed code alongside a standalone link." },
        { q: "Does a virtual tour replace photography?", a: "No — it complements standard photography rather than replacing it." },
        { q: "Can you add hotspots with extra information?", a: "Yes, informational hotspots can be added at key points in the tour." },
        { q: "How long is the tour hosted for?", a: "Hosting terms are agreed per project — ask about ongoing hosting if you need the tour live long-term." },
      ],
      related: [
        { label: "Villa Photography", href: "/villas-real-estate/villa-photography", description: "Standard photography to pair with the tour." },
        { label: "Property Video", href: "/villas-real-estate/property-video", description: "A filmed alternative to a self-navigated tour." },
        { label: "Villa Website", href: "/websites-digital/villa-website", description: "A website built to embed the tour and gallery." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "marketing",
      hubSlug: "villas-real-estate",
      navLabel: "Real Estate Marketing",
      h1: "Real Estate Marketing on Koh Phangan",
      primaryKeyword: "real estate marketing Koh Phangan",
      secondaryTopics: ["villa marketing", "property promotion"],
      metaTitle: "Real Estate Marketing Koh Phangan | Villa & Property",
      metaDescription:
        "Full property marketing on Koh Phangan — visuals, listing copy, social content, advertising and local visibility in one program.",
      directAnswer:
        "We run full property marketing programs for villas and developments on Koh Phangan — combining photography, video, listing copy, social content, advertising and local visibility into one coordinated plan, rather than a single deliverable.",
      heroSupport: "Photography, listing content, social media and advertising coordinated into one property marketing plan.",
      heroImage: images.team,
      heroImageAlt: "Team planning a real estate marketing campaign",
      scope: [
        { title: "Visual production", description: "Photography, video, drone and virtual tours as needed." },
        { title: "Listing content", description: "Copy and structure for listing platforms and your own website." },
        { title: "Social media", description: "A content plan built specifically around the property or portfolio." },
        { title: "Advertising", description: "Paid campaigns targeting relevant buyer or renter audiences." },
        { title: "Local visibility", description: "Local SEO and Google Business Profile support where relevant." },
      ],
      benefits: [
        { title: "One coordinated campaign", description: "Every channel uses the same visuals and messaging." },
        { title: "Faster results", description: "A full marketing push typically outperforms photography alone." },
        { title: "Scales across a portfolio", description: "Works for a single villa or a full portfolio of listings." },
        { title: "Measurable", description: "Tracking in place so you can see what's actually generating inquiries." },
      ],
      process: [
        { title: "Discovery", description: "Understand the property, target buyer/renter and timeline." },
        { title: "Production", description: "Photography, video and any additional assets are produced." },
        { title: "Launch", description: "Listing content, social and advertising go live together." },
        { title: "Optimize", description: "Ongoing adjustment based on inquiries and engagement." },
      ],
      pricing: [
        { service: "Property marketing package (single villa)", range: "THB 35,000 – 80,000", note: "Visuals + listing + social + launch advertising" },
        { service: "Portfolio marketing (multiple properties)", range: "Custom", note: "Scoped per portfolio size" },
      ],
      useCases: [
        { title: "Villa owners selling or renting", description: "A complete marketing push rather than photography alone." },
        { title: "Developers", description: "Pre-sale and launch marketing for a development." },
        { title: "Agencies", description: "A turnkey marketing service to offer premium listings." },
      ],
      faqs: [
        { q: "Do I need to use all your production services, or can I bring my own?", a: "You can bring existing assets — we'll fill gaps and build the marketing plan around what you have." },
        { q: "How long does a full property marketing campaign take to launch?", a: "Typically 2–4 weeks from kickoff to a fully live campaign, depending on production needs." },
        { q: "Is advertising spend included in the package price?", a: "No — the package covers production and management; ad spend is billed separately, directly to the platform." },
        { q: "Can this work for a portfolio of several villas at once?", a: "Yes — portfolio marketing is scoped individually based on the number of properties." },
        { q: "Do you handle listing on platforms like Airbnb or agency sites?", a: "We produce the content and copy; publishing to specific platforms is coordinated with you or your agent." },
        { q: "How do you measure whether the campaign is working?", a: "Inquiries, views and, where trackable, bookings or offers — reported on a regular schedule." },
      ],
      related: [
        { label: "Villa Photography", href: "/villas-real-estate/villa-photography", description: "The visual foundation of the marketing plan." },
        { label: "Villa Website", href: "/websites-digital/villa-website", description: "A dedicated website for the property." },
        { label: "Meta Ads", href: "/advertising/meta-ads", description: "Paid social reach for the listing." },
      ],
      finalCtaLabel: "Discuss Your Project",
    },
  ],
};
