import { images } from "@/assets/images";
import type { HubPage } from "@/content/types";

export const websitesDigitalHub: HubPage = {
  slug: "websites-digital",
  navLabel: "Websites & Digital",
  order: 6,
  priority: "P0",
  h1: "Web Design on Koh Phangan",
  primaryKeyword: "web design Koh Phangan",
  metaTitle: "Web Design Koh Phangan | Websites, SEO & AI Search",
  metaDescription:
    "Website design, landing pages, technical SEO and AI search optimization for businesses on Koh Phangan — built for real conversion, not just looks.",
  directAnswer:
    "CreativeLAB designs and builds websites for Koh Phangan businesses — from single landing pages to full business and e-commerce sites — combined with technical SEO and AI search visibility so the site is actually found, not just well-designed.",
  heroSupport:
    "Websites, landing pages, SEO and AI search visibility for businesses that need a site that performs, not just looks good.",
  heroImage: images.studio,
  heroImageAlt: "Website design being reviewed on a laptop screen",
  editorialTitle: "A website is infrastructure, not a brochure",
  editorialBody: [
    "A website that just describes your business isn't doing much work. The sites that perform are structured around what a visitor actually needs to do next — book, inquire, order — and are built so search engines and, increasingly, AI answer engines can understand and recommend them.",
    "We combine editorial design with the technical fundamentals — clean structure, fast loading, semantic HTML, proper schema — so the site looks premium and is genuinely visible where your customers are searching.",
  ],
  faqs: [
    { q: "Do you build the website, or just design it?", a: "Both — design and development are handled by the same team for a coherent result." },
    { q: "What platform do you build on?", a: "We choose a modern, SEO-safe, static-first framework suited to the project rather than defaulting to one platform regardless of fit." },
    { q: "Can you redesign our existing website instead of starting from scratch?", a: "Yes, through our Website Redesign service, with care taken not to lose existing SEO value." },
    { q: "Do you handle hosting?", a: "We can set up and hand over hosting, or continue managing it — we'll agree what fits your situation." },
    { q: "Is SEO included, or a separate cost?", a: "On-page SEO fundamentals are included in every build; deeper technical SEO work is scoped separately for complex sites." },
    { q: "How long does a typical website project take?", a: "From 2 weeks for a landing page to 6–10 weeks for a larger multi-page or e-commerce site." },
  ],
  finalCtaLabel: "Start a Project",
  services: [
    {
      slug: "web-design",
      hubSlug: "websites-digital",
      navLabel: "Web Design",
      h1: "Web Design on Koh Phangan",
      primaryKeyword: "web design Koh Phangan",
      secondaryTopics: ["website development", "business websites"],
      metaTitle: "Web Design Koh Phangan | CreativeLAB",
      metaDescription:
        "Web design for Koh Phangan businesses — responsive, SEO-ready websites built around clear user experience and conversion.",
      directAnswer:
        "We design and build websites for Koh Phangan businesses — responsive, fast-loading sites with clear information architecture and SEO-ready structure from day one, not bolted on afterward.",
      heroSupport: "Responsive, SEO-ready web design built around clear user experience.",
      heroImage: images.studio,
      heroImageAlt: "Web design mockups displayed on a screen",
      scope: [
        { title: "UX & information architecture", description: "A clear structure that gets visitors to the right page fast." },
        { title: "Responsive design", description: "A site that works properly from mobile through desktop." },
        { title: "SEO-ready structure", description: "Semantic HTML, proper headings and metadata from the start." },
        { title: "Performance-first build", description: "Fast loading as a design constraint, not an afterthought." },
      ],
      benefits: [
        { title: "Built to convert", description: "Design decisions are made around your business goal, not aesthetics alone." },
        { title: "SEO from day one", description: "No costly retrofit of structure and metadata after launch." },
        { title: "Fast on mobile", description: "Most visitors browse on their phone — performance is prioritized accordingly." },
        { title: "Consistent with your brand", description: "Visual identity carried through from your other marketing." },
      ],
      process: [
        { title: "Discovery", description: "Understand your goals, audience and content." },
        { title: "Design", description: "Wireframes and visual design reviewed with you." },
        { title: "Build", description: "Development with performance and SEO built in." },
        { title: "Launch", description: "Testing, then go-live with analytics in place." },
      ],
      pricing: [
        { service: "Website design (5-page landing)", range: "THB 40,000 – 100,000", note: "Responsive + SEO-ready" },
        { service: "Website design (multi-page business site)", range: "THB 90,000 – 180,000", note: "8–15 pages, CMS-ready" },
      ],
      useCases: [
        { title: "New businesses", description: "A complete, professional web presence from launch." },
        { title: "Businesses without a real website", description: "Replacing a social-only presence with a proper site." },
        { title: "Rebrands", description: "A new site to match an updated brand identity." },
      ],
      faqs: [
        { q: "Do I need to provide the content, or do you write it?", a: "We write the copy following our content rules; you provide the facts and any material we can't invent (pricing, credentials, etc.)." },
        { q: "Will the site be easy for me to update later?", a: "Yes, we structure content to be CMS-ready or straightforward to hand over for edits." },
        { q: "Can you match our existing brand identity?", a: "Yes, or we can develop one together through our Branding service if you don't have one yet." },
        { q: "Do you provide photography for the site?", a: "Yes, through our photography services, or we can work with assets you already have." },
        { q: "What happens after launch — do you offer support?", a: "We can agree an ongoing support arrangement, or hand over full documentation for your own team." },
        { q: "How many revision rounds are included?", a: "Typically two structured revision rounds at the design stage are included." },
      ],
      related: [
        { label: "Landing Pages", href: "/websites-digital/landing-pages", description: "A focused single-page alternative." },
        { label: "Technical SEO", href: "/websites-digital/technical-seo", description: "Deeper SEO work for larger sites." },
        { label: "Branding", href: "/branding-creative/branding", description: "Brand identity to inform the design." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "business-websites",
      hubSlug: "websites-digital",
      navLabel: "Business Websites",
      h1: "Business Website Design on Koh Phangan",
      primaryKeyword: "business website Koh Phangan",
      secondaryTopics: ["company website", "service website"],
      metaTitle: "Business Website Koh Phangan | Company Websites",
      metaDescription:
        "Multi-page business websites for Koh Phangan companies — information architecture, conversion paths and CMS built for growth.",
      directAnswer:
        "We build multi-page business websites for Koh Phangan companies — structured information architecture across services, about and contact pages, built on a CMS so your team can update content without needing a developer for every change.",
      heroSupport: "A structured, CMS-ready website for a company with more than one service or story to tell.",
      heroImage: images.studio,
      heroImageAlt: "Business website homepage displayed on a monitor",
      scope: [
        { title: "Information architecture", description: "A logical site structure across services, about and contact." },
        { title: "Conversion paths", description: "Clear routes to inquiry or contact from every key page." },
        { title: "CMS setup", description: "Content structured so your team can make updates independently." },
        { title: "On-page SEO", description: "Metadata, headings and structure for each page." },
      ],
      benefits: [
        { title: "Room to grow", description: "A structure that can expand as your services or content grow." },
        { title: "Independent content updates", description: "No developer needed for routine content changes." },
        { title: "Clear conversion paths", description: "Every page has an obvious next step for the visitor." },
        { title: "Professional first impression", description: "A site that reflects a serious, established business." },
      ],
      process: [
        { title: "Discovery", description: "Map out your services, audience and content needs." },
        { title: "Architecture & design", description: "Structure and visual design for the full site." },
        { title: "Build & CMS setup", description: "Development with a content system your team can use." },
        { title: "Launch & train", description: "Go live, with a walkthrough of how to manage content." },
      ],
      pricing: [
        { service: "Business website (8–12 pages)", range: "THB 70,000 – 140,000", note: "CMS-ready, on-page SEO included" },
      ],
      useCases: [
        { title: "Multi-service companies", description: "Businesses with several distinct services to present clearly." },
        { title: "B2B and professional services", description: "A credible, structured site for a professional audience." },
        { title: "Growing local companies", description: "Businesses outgrowing a single-page or social-only presence." },
      ],
      faqs: [
        { q: "What CMS do you use?", a: "We select a system suited to your team's technical comfort and the site's needs, and document it clearly at handover." },
        { q: "Can I edit the site myself after launch?", a: "Yes, that's the point of the CMS setup — we'll train you on how." },
        { q: "Do you write all the page content?", a: "Yes, following our copy rules, based on information and facts you provide." },
        { q: "Can this integrate with our existing tools (CRM, booking, etc.)?", a: "In many cases yes — tell us what you use and we'll advise on integration options." },
        { q: "How many pages does a typical business website include?", a: "Most range from 8–15 pages depending on how many services and locations you cover." },
        { q: "Do you offer ongoing maintenance after launch?", a: "Yes, as an optional ongoing arrangement." },
      ],
      related: [
        { label: "Web Design", href: "/websites-digital/web-design", description: "The core design and build service this extends." },
        { label: "Technical SEO", href: "/websites-digital/technical-seo", description: "Deeper SEO support as the site grows." },
        { label: "Website Redesign", href: "/websites-digital/redesign", description: "If you already have a site that needs rebuilding." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "landing-pages",
      hubSlug: "websites-digital",
      navLabel: "Landing Pages",
      h1: "Landing Page Design on Koh Phangan",
      primaryKeyword: "landing page design Koh Phangan",
      secondaryTopics: ["campaign landing page", "lead generation"],
      metaTitle: "Landing Page Design Koh Phangan | Campaign Pages",
      metaDescription:
        "Landing pages for Koh Phangan advertising campaigns — message-matched, fast-loading pages built to convert traffic into leads.",
      directAnswer:
        "We design landing pages built specifically for advertising campaigns — message-matched to your ad creative, fast-loading, and structured around one clear conversion action, rather than sending paid traffic to a generic homepage.",
      heroSupport: "Message-matched, fast-loading pages built around one clear conversion action.",
      heroImage: images.studio,
      heroImageAlt: "Landing page design shown on a laptop and phone",
      scope: [
        { title: "Message match", description: "Page headline and content aligned with the ad that brought the visitor." },
        { title: "Single clear CTA", description: "One conversion action, without competing distractions." },
        { title: "Tracking setup", description: "Conversion tracking configured before the page goes live." },
        { title: "Fast load time", description: "Built lean to protect ad quality scores and conversion rate." },
      ],
      benefits: [
        { title: "Higher conversion rate", description: "Message-matched pages consistently outperform generic homepages for ad traffic." },
        { title: "Better ad platform scores", description: "Fast, relevant landing pages support stronger Google/Meta ad performance." },
        { title: "Clear measurement", description: "Tracking built in from the start, not added as an afterthought." },
        { title: "Fast to produce", description: "A focused single page can launch much faster than a full site rebuild." },
      ],
      process: [
        { title: "Brief", description: "Understand the campaign, offer and audience." },
        { title: "Design", description: "A focused single-purpose page layout." },
        { title: "Build & track", description: "Development with conversion tracking configured." },
        { title: "Launch", description: "Page goes live in time for the campaign." },
      ],
      pricing: [
        { service: "Landing page (single offer)", range: "THB 15,000 – 35,000", note: "Includes tracking setup" },
        { service: "Landing page set (multiple variants)", range: "THB 30,000 – 60,000", note: "For A/B testing different offers" },
      ],
      useCases: [
        { title: "Advertising campaigns", description: "A dedicated page for Google or Meta Ads traffic." },
        { title: "Seasonal offers", description: "A time-boxed page for a specific promotion." },
        { title: "Lead generation", description: "A focused page built purely to capture inquiries." },
      ],
      faqs: [
        { q: "Can this be built quickly for a time-sensitive campaign?", a: "Yes, a single landing page can typically be delivered faster than a full website project." },
        { q: "Do you handle the advertising too?", a: "Yes, through our Advertising services — landing pages and campaigns are often built together." },
        { q: "Can I run multiple landing page variants for testing?", a: "Yes, we can build variants specifically for A/B testing." },
        { q: "Does this include the ad creative?", a: "Ad creative is part of our Advertising services; this covers the page traffic lands on." },
        { q: "Will this page be indexed by Google?", a: "We can set it to index or noindex depending on whether you want it discoverable organically." },
        { q: "Can an existing landing page be improved instead of rebuilt?", a: "Yes, we can audit and optimize an existing page rather than starting fresh." },
      ],
      related: [
        { label: "Google Ads", href: "/advertising/google-ads", description: "Search campaigns that can point to this page." },
        { label: "Meta Ads", href: "/advertising/meta-ads", description: "Social campaigns that can point to this page." },
        { label: "Performance Marketing", href: "/advertising/performance", description: "Ongoing testing and optimization." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "restaurant-website",
      hubSlug: "websites-digital",
      navLabel: "Restaurant Website",
      h1: "Restaurant Website Development on Koh Phangan",
      primaryKeyword: "restaurant website Koh Phangan",
      secondaryTopics: ["menu website", "online ordering", "booking"],
      metaTitle: "Restaurant Website Development Koh Phangan",
      metaDescription:
        "Technical website development for Koh Phangan restaurants — menu structure, booking and ordering integration, built for performance.",
      directAnswer:
        "We build the technical foundation of a restaurant website — fast page loads, structured menu data, and integration with your booking or ordering platform — as a standalone development project or alongside our Food & Restaurants marketing team.",
      heroSupport: "Fast, well-structured restaurant website development, integrated with your booking or ordering platform.",
      heroImage: images.food,
      heroImageAlt: "Restaurant website structure being developed",
      scope: [
        { title: "Menu data structure", description: "Menu content structured for easy updates and SEO." },
        { title: "Booking/ordering integration", description: "Connecting your chosen reservation or delivery platform." },
        { title: "Performance optimization", description: "Fast load times, especially on mobile." },
        { title: "SEO foundation", description: "Schema and metadata suited to restaurant search behavior." },
      ],
      benefits: [
        { title: "Technical reliability", description: "A properly engineered site rather than a fragile page builder." },
        { title: "Faster mobile experience", description: "Most diners browse restaurant sites on their phone." },
        { title: "Structured for search", description: "Restaurant-specific schema supports rich search results." },
        { title: "Works with your existing tools", description: "Integrates with the booking/ordering system you already use." },
      ],
      process: [
        { title: "Technical scoping", description: "Confirm platform integrations and performance requirements." },
        { title: "Build", description: "Development of the site's technical foundation." },
        { title: "Integrate", description: "Connect booking/ordering and menu data sources." },
        { title: "Launch & test", description: "Performance and functionality testing before go-live." },
      ],
      pricing: [
        { service: "Restaurant site development", range: "THB 35,000 – 80,000", note: "Technical build, integrations included" },
      ],
      useCases: [
        { title: "Restaurants needing a technical rebuild", description: "Replacing a slow or unreliable existing site." },
        { title: "Multi-location restaurant groups", description: "A consistent technical platform across locations." },
        { title: "Restaurants adding online ordering", description: "Integrating a new ordering system into the site." },
      ],
      faqs: [
        { q: "How is this different from your Food & Restaurants website service?", a: "This is the technical development side; the Food & Restaurants version bundles it with menu/marketing strategy for restaurants specifically." },
        { q: "Can you integrate with our existing POS or ordering system?", a: "In most cases yes — tell us what you use and we'll confirm integration options." },
        { q: "Do you also design the site, or only build it?", a: "We handle both design and development, or can build from an existing design if you have one." },
        { q: "How fast will the site load?", a: "We target strong Core Web Vitals scores as a hard requirement, not an afterthought." },
        { q: "Can the menu be updated without a developer?", a: "Yes, menu content is structured to be editable by your team." },
        { q: "Do you handle multilingual menus?", a: "Yes, the technical structure supports multiple languages when needed." },
      ],
      related: [
        { label: "Restaurant Website", href: "/food-restaurants/website", description: "The marketing-led version of this service." },
        { label: "Technical SEO", href: "/websites-digital/technical-seo", description: "Deeper SEO support if needed." },
        { label: "Menu Design", href: "/food-restaurants/menu-design", description: "Visual menu design to feed into the site." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "villa-website",
      hubSlug: "websites-digital",
      navLabel: "Villa Website",
      h1: "Villa Website Development on Koh Phangan",
      primaryKeyword: "villa website Koh Phangan",
      secondaryTopics: ["property website", "booking"],
      metaTitle: "Villa Website Development Koh Phangan",
      metaDescription:
        "Villa and property websites on Koh Phangan — gallery, property information and booking or inquiry integration, built for performance.",
      directAnswer:
        "We build websites for individual villas and small property portfolios on Koh Phangan — a strong photo gallery, clear property information, and a direct path to inquire or book, technically built to load fast on the mobile connections most travellers use.",
      heroSupport: "A gallery-led villa website with a clear, fast path to inquire or book.",
      heroImage: images.photoshoot,
      heroImageAlt: "Villa website gallery displayed on a screen",
      scope: [
        { title: "Photo & video gallery", description: "A fast-loading, well-organized showcase of the property." },
        { title: "Property information", description: "Clear layout of rooms, amenities and location details." },
        { title: "Booking/inquiry integration", description: "A direct connection to your booking platform or inquiry form." },
        { title: "Virtual tour embedding", description: "Support for embedding a 360° tour if you have one." },
      ],
      benefits: [
        { title: "Shows the property at its best", description: "A gallery-first structure suited to how travellers evaluate villas." },
        { title: "Fast on mobile connections", description: "Built for travellers browsing on variable mobile networks." },
        { title: "One clear next step", description: "A direct, unambiguous path to inquire or book." },
        { title: "Works with your booking system", description: "Integrates with the platform you already use." },
      ],
      process: [
        { title: "Discovery", description: "Understand the property, audience and booking flow." },
        { title: "Design", description: "A gallery-led layout suited to the property's character." },
        { title: "Build & integrate", description: "Development with booking/inquiry integration." },
        { title: "Launch", description: "Testing and go-live, including on mobile networks." },
      ],
      pricing: [
        { service: "Villa website (single property)", range: "THB 35,000 – 75,000", note: "Gallery, info, booking integration" },
        { service: "Villa portfolio website", range: "THB 60,000 – 130,000", note: "Multiple properties, shared platform" },
      ],
      useCases: [
        { title: "Independent villa owners", description: "A dedicated site beyond listing platforms alone." },
        { title: "Small property portfolios", description: "One site representing several villas." },
        { title: "Villas for sale", description: "A marketing-focused site for a property on the market." },
      ],
      faqs: [
        { q: "Can this replace or complement our Airbnb listing?", a: "It complements it — a dedicated site builds direct bookings alongside platform listings." },
        { q: "Do you include the photography?", a: "Yes, through our Villa Photography and Property Video services, or using assets you already have." },
        { q: "Can you embed a 360 virtual tour?", a: "Yes, if you have one from our Virtual Tours service or elsewhere." },
        { q: "Which booking systems do you integrate with?", a: "Most common booking and inquiry tools — tell us what you use and we'll confirm compatibility." },
        { q: "Will the site work well for international visitors on slow connections?", a: "Yes, performance for varied connection speeds is a specific priority for this type of site." },
        { q: "Can this be a multilingual site?", a: "Yes, if your guest audience needs more than one language." },
      ],
      related: [
        { label: "Villa Photography", href: "/villas-real-estate/villa-photography", description: "The photography behind the gallery." },
        { label: "Virtual Tours", href: "/villas-real-estate/virtual-tours", description: "A 360 tour to embed on the site." },
        { label: "Real Estate Marketing", href: "/villas-real-estate/marketing", description: "Full marketing built around the site." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "ecommerce",
      hubSlug: "websites-digital",
      navLabel: "E-commerce",
      h1: "E-commerce Website Development on Koh Phangan",
      primaryKeyword: "ecommerce website Koh Phangan",
      secondaryTopics: ["online shop", "product website"],
      metaTitle: "E-commerce Website Koh Phangan | Online Shop",
      metaDescription:
        "E-commerce website development for Koh Phangan businesses — product catalog, checkout and mobile-first shopping experience.",
      directAnswer:
        "We build e-commerce websites for Koh Phangan businesses selling products online — a clear product catalog, a straightforward checkout, and a mobile-first shopping experience, backed by a platform your team can manage independently.",
      heroSupport: "A product catalog and checkout built for how customers actually shop on their phones.",
      heroImage: images.studio,
      heroImageAlt: "E-commerce product catalog displayed on a phone",
      scope: [
        { title: "Product catalog", description: "Clear categorization and product presentation." },
        { title: "Checkout flow", description: "A straightforward, low-friction path to purchase." },
        { title: "Payment integration", description: "Connecting the payment provider suited to your business." },
        { title: "Mobile-first UX", description: "A shopping experience designed for phone screens first." },
      ],
      benefits: [
        { title: "Lower cart abandonment", description: "A clean, simple checkout reduces friction at the point of sale." },
        { title: "Easier product management", description: "A platform your team can update without a developer for routine changes." },
        { title: "Built for mobile shoppers", description: "Most online shopping traffic arrives on a phone." },
        { title: "Scalable foundation", description: "A structure that can grow with your product range." },
      ],
      process: [
        { title: "Discovery", description: "Understand your products, catalog size and payment needs." },
        { title: "Design", description: "Catalog and checkout UX designed around your products." },
        { title: "Build & integrate", description: "Development with payment and inventory integration." },
        { title: "Launch", description: "Testing across devices before go-live." },
      ],
      pricing: [
        { service: "E-commerce site (small catalog)", range: "THB 60,000 – 120,000", note: "Up to ~50 products" },
        { service: "E-commerce site (larger catalog)", range: "THB 120,000 – 220,000", note: "50+ products, more complex catalog" },
      ],
      useCases: [
        { title: "Local product brands", description: "Selling physical products directly to customers online." },
        { title: "Businesses adding online sales", description: "Moving from in-person only to also selling online." },
        { title: "Multi-product retailers", description: "A structured catalog for a wider product range." },
      ],
      faqs: [
        { q: "Which payment providers can you integrate?", a: "Common providers suited to Thai and international customers — tell us your preference and we'll confirm compatibility." },
        { q: "Can I manage products and inventory myself?", a: "Yes, the platform is set up so your team can manage the catalog directly." },
        { q: "Do you handle shipping calculation?", a: "Yes, we configure shipping options and rates as part of the build." },
        { q: "Can this integrate with an existing POS system?", a: "In many cases yes — tell us what you use and we'll advise on integration." },
        { q: "How long does an e-commerce build take?", a: "Typically 6–10 weeks depending on catalog size and integrations." },
        { q: "Do you offer ongoing support after launch?", a: "Yes, as an optional ongoing arrangement for updates and maintenance." },
      ],
      related: [
        { label: "Web Design", href: "/websites-digital/web-design", description: "Our broader web design service." },
        { label: "Landing Pages", href: "/websites-digital/landing-pages", description: "For promoting specific products or offers." },
        { label: "Meta Ads", href: "/advertising/meta-ads", description: "Drive traffic to your online shop." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "redesign",
      hubSlug: "websites-digital",
      navLabel: "Website Redesign",
      h1: "Website Redesign on Koh Phangan",
      primaryKeyword: "website redesign Koh Phangan",
      secondaryTopics: ["UX redesign", "website optimization"],
      metaTitle: "Website Redesign Koh Phangan | UX & SEO Migration",
      metaDescription:
        "Website redesign for Koh Phangan businesses — audit, restructure and rebuild without losing existing SEO value.",
      directAnswer:
        "We redesign existing websites for Koh Phangan businesses — auditing what's underperforming, restructuring content and design, and migrating carefully so the SEO value you've already built isn't lost in the process.",
      heroSupport: "A careful redesign that fixes what's underperforming without losing your existing SEO value.",
      heroImage: images.studio,
      heroImageAlt: "Before and after website redesign comparison",
      scope: [
        { title: "Audit", description: "Identify what's underperforming in design, content and technical structure." },
        { title: "Restructure", description: "A revised information architecture based on the audit's findings." },
        { title: "Redesign", description: "Updated visual design consistent with your current brand." },
        { title: "Safe migration", description: "Redirects and technical checks so SEO value carries over." },
      ],
      benefits: [
        { title: "Fixes what's actually broken", description: "The audit ensures the redesign solves real problems, not assumed ones." },
        { title: "SEO-safe migration", description: "Careful redirects protect existing search rankings during the switch." },
        { title: "Modernized without starting over", description: "Keeps what's working while improving what isn't." },
        { title: "Better performance", description: "An opportunity to fix technical debt that's built up over time." },
      ],
      process: [
        { title: "Audit", description: "Review analytics, SEO performance and user feedback on the current site." },
        { title: "Plan", description: "Define what changes and what's preserved." },
        { title: "Redesign & rebuild", description: "Design and development of the updated site." },
        { title: "Migrate", description: "Careful launch with redirects and monitoring in place." },
      ],
      pricing: [
        { service: "Website redesign audit", range: "THB 10,000 – 20,000", note: "One-time, with a written action plan" },
        { service: "Full redesign & rebuild", range: "THB 60,000 – 150,000", note: "Depends on site size and complexity" },
      ],
      useCases: [
        { title: "Outdated websites", description: "Sites that no longer reflect the business or perform well." },
        { title: "Sites losing search visibility", description: "Redesigns that address underlying technical SEO issues." },
        { title: "Rebrands", description: "Aligning an existing site with a new visual identity." },
      ],
      faqs: [
        { q: "Will we lose our current search rankings during a redesign?", a: "Not if migrated carefully — proper redirects and technical checks are core to how we handle this." },
        { q: "Do you keep any of the existing content?", a: "Yes, where it's performing well; the audit identifies what to keep, revise or replace." },
        { q: "How do you decide what needs to change?", a: "Based on an audit of analytics, user behavior and technical SEO — not just visual preference." },
        { q: "Can this include a full technical SEO overhaul?", a: "Yes, often bundled together when a redesign is being planned." },
        { q: "How long does a redesign project take?", a: "Typically 6–12 weeks depending on the site's size and complexity." },
        { q: "Do you provide before/after performance data?", a: "Yes, we track key metrics before and after launch to measure the impact." },
      ],
      related: [
        { label: "Technical SEO", href: "/websites-digital/technical-seo", description: "Often bundled with a redesign." },
        { label: "Web Design", href: "/websites-digital/web-design", description: "Our core design and build service." },
        { label: "AI Search / GEO", href: "/websites-digital/ai-search", description: "Improve visibility in AI-powered search too." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "technical-seo",
      hubSlug: "websites-digital",
      navLabel: "Technical SEO",
      h1: "Technical SEO on Koh Phangan",
      primaryKeyword: "technical SEO Koh Phangan",
      secondaryTopics: ["crawlability", "indexing", "Core Web Vitals"],
      metaTitle: "Technical SEO Koh Phangan | Core Web Vitals & Schema",
      metaDescription:
        "Technical SEO for Koh Phangan business websites — crawlability, indexing, structured data and Core Web Vitals fixes.",
      directAnswer:
        "We fix the technical foundations that determine whether search engines can properly crawl, index and understand your website — canonical tags, sitemaps, structured data and Core Web Vitals — the unglamorous work that underpins everything else in SEO.",
      heroSupport: "Crawlability, indexing, structured data and Core Web Vitals fixed properly.",
      heroImage: images.studio,
      heroImageAlt: "Technical SEO audit results on a dashboard",
      scope: [
        { title: "Crawlability & indexing", description: "Ensuring search engines can properly access and index your pages." },
        { title: "Canonical & sitemap setup", description: "Clean canonical tags and an accurate XML sitemap." },
        { title: "Structured data", description: "Schema markup implemented correctly for your page types." },
        { title: "Core Web Vitals", description: "Fixing performance issues affecting LCP, INP and CLS." },
      ],
      benefits: [
        { title: "Removes hidden blockers", description: "Technical issues often silently limit how well content can rank." },
        { title: "Better search appearance", description: "Structured data supports rich results and clearer listings." },
        { title: "Faster, more stable pages", description: "Core Web Vitals fixes improve real user experience too." },
        { title: "A solid foundation", description: "Every other SEO and content effort performs better on healthy technical ground." },
      ],
      process: [
        { title: "Technical audit", description: "Full crawl and analysis of your site's technical health." },
        { title: "Prioritize", description: "Rank issues by impact so the highest-value fixes come first." },
        { title: "Fix", description: "Implement corrections across code, markup and configuration." },
        { title: "Verify", description: "Confirm fixes resolved the issues using real crawl and speed data." },
      ],
      pricing: [
        { service: "Technical SEO audit", range: "THB 12,000 – 25,000", note: "Full site crawl with prioritized findings" },
        { service: "Technical SEO implementation", range: "THB 15,000 – 45,000", note: "Depends on issue volume and site size" },
      ],
      useCases: [
        { title: "Sites with declining organic traffic", description: "Identifying and fixing what's holding the site back." },
        { title: "Larger multi-page sites", description: "Complex sites where technical issues compound at scale." },
        { title: "Pre-launch checks", description: "Catching issues before a new site goes live." },
      ],
      faqs: [
        { q: "Do you need access to our website's code?", a: "Yes, or to work directly within your CMS/platform, depending on the site." },
        { q: "How is this different from Local SEO?", a: "Technical SEO focuses on your website's structure and crawlability; Local SEO focuses on local search and Maps visibility specifically." },
        { q: "Can you fix Core Web Vitals issues without a full rebuild?", a: "Often yes — many Core Web Vitals issues can be fixed without a full redesign." },
        { q: "Do you implement schema markup for us?", a: "Yes, implementation is included, not just recommendations." },
        { q: "How long until we see ranking improvements?", a: "Technical fixes can improve crawlability quickly; ranking impact typically builds over 1–3 months." },
        { q: "Is this a one-time project or ongoing?", a: "It can be either — a one-time audit and fix, or ongoing monitoring as the site evolves." },
      ],
      related: [
        { label: "Website Redesign", href: "/websites-digital/redesign", description: "Often paired with a technical SEO overhaul." },
        { label: "AI Search / GEO", href: "/websites-digital/ai-search", description: "Extends technical work into AI search visibility." },
        { label: "Performance Marketing", href: "/advertising/performance", description: "Measurement across the whole funnel." },
      ],
      finalCtaLabel: "Request a Quote",
    },
    {
      slug: "ai-search",
      hubSlug: "websites-digital",
      navLabel: "AI Search",
      h1: "AI Search Optimization (GEO) on Koh Phangan",
      primaryKeyword: "AI search optimization Koh Phangan",
      secondaryTopics: ["GEO", "AI visibility", "entity optimization"],
      metaTitle: "AI Search Optimization Koh Phangan | GEO",
      metaDescription:
        "AI search / Generative Engine Optimization for Koh Phangan businesses — structured, machine-readable content built to be cited by AI answer engines.",
      directAnswer:
        "We optimize websites so AI answer engines like ChatGPT, Perplexity and Google's AI Overviews can understand, trust and cite your business — clear entity definitions, structured direct-answer content, and machine-readable markup, alongside traditional SEO rather than instead of it.",
      heroSupport: "Structured, machine-readable content built to be understood and cited by AI answer engines.",
      heroImage: images.studio,
      heroImageAlt: "Structured content displayed for AI search optimization",
      scope: [
        { title: "Entity clarity", description: "Clear, consistent definitions of who you are and what you do." },
        { title: "Direct-answer content", description: "Concise, factual answers positioned where AI systems can extract them." },
        { title: "Structured data", description: "Schema markup that reinforces entity and service information." },
        { title: "Crawler access", description: "Allowing relevant AI crawlers appropriate access via robots.txt." },
      ],
      benefits: [
        { title: "Visibility in AI answers", description: "A growing share of discovery now happens through AI-generated answers, not just search results." },
        { title: "Reinforces traditional SEO", description: "The same clarity and structure benefits both AI and standard search." },
        { title: "Future-facing investment", description: "Positions your site for a search landscape that's actively shifting." },
        { title: "Built on facts, not manipulation", description: "We strengthen genuine clarity rather than attempting to game AI systems." },
      ],
      process: [
        { title: "Audit", description: "Assess current entity clarity and structured data." },
        { title: "Structure content", description: "Rewrite key sections as clear, self-contained direct answers." },
        { title: "Implement schema", description: "Add or strengthen structured data across key pages." },
        { title: "Monitor", description: "Track visibility in AI-generated answers where measurable." },
      ],
      pricing: [
        { service: "AI search optimization audit", range: "THB 10,000 – 20,000", note: "One-time, with a written action plan" },
        { service: "AI search optimization implementation", range: "THB 15,000 – 35,000", note: "Content and schema changes across key pages" },
      ],
      useCases: [
        { title: "Service businesses", description: "Being clearly and accurately described when someone asks an AI assistant." },
        { title: "Established local brands", description: "Reinforcing entity authority across AI and traditional search." },
        { title: "Businesses investing in long-term SEO", description: "Adding AI visibility to an existing SEO strategy." },
      ],
      faqs: [
        { q: "What is GEO / AI search optimization?", a: "Generative Engine Optimization — structuring content so AI systems that generate answers (rather than just list links) can understand and cite your business accurately." },
        { q: "Does this replace traditional SEO?", a: "No — it complements it. The same clarity and structure typically helps both." },
        { q: "Can you guarantee my business will be mentioned by ChatGPT or similar tools?", a: "No — we never fabricate guarantees; we implement the structural and content best practices known to support AI visibility." },
        { q: "Do I need to block or allow specific AI crawlers?", a: "We configure robots.txt to allow relevant AI crawlers (like GPTBot and ClaudeBot) where that supports your visibility goals." },
        { q: "Is this only relevant for large businesses?", a: "No — clear, well-structured content on any size site can be picked up by AI answer engines." },
        { q: "How do you measure results here?", a: "Where tools allow it, we track mentions and citations; otherwise we track the underlying content and structure improvements." },
      ],
      related: [
        { label: "Technical SEO", href: "/websites-digital/technical-seo", description: "The technical foundation this builds on." },
        { label: "Website Redesign", href: "/websites-digital/redesign", description: "A chance to build AI-readiness in from the start." },
        { label: "Local SEO", href: "/business-local-presence/local-seo", description: "Complementary local search visibility." },
      ],
      finalCtaLabel: "Request a Quote",
    },
  ],
};
